### ISSUE TITLE
The Quick Introduction doesn't seem to work for me? The program just hangs and outputs nothing, nor errors out

### ISSUE THREAD

**Issue by adrianocr** [facebook/ent#1007]
Quick introduction at https://entgo.io/docs/getting-started/

So my steps were the following:
- mkdir enttest
- cd enttest
- go mod init enttest
- go get github.com/facebook/ent/cmd/ent
- entc init User
- edit the Fields() function in ent/schema/user.go to:

```
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("age").
			Positive(),
		field.String("name").
			Default("unknown"),
	}
}
```

- run `go generate ./ent`
- created a main.go file that looks like this:

```
package main

import (
	"context"
	"enttest/ent"
	"fmt"
	_ "github.com/lib/pq"
	"log"
)

func CreateUser(ctx context.Context, client *ent.Client) (*ent.User, error) {
	u, err := client.User.
		Create().
		SetAge(30).
		SetName("adriano").
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed creating user: %v", err)
	}
	log.Println("user was created: ", u)
	return u, nil
}

func main() {
	var ctx context.Context
	client, err := ent.Open("postgres", "host=localhost port=5432 user=adriano dbname=enttest password=XXXXXXXXXXXXXX sslmode=disable")
	if err != nil {
		log.Fatalf("failed opening connection to sqlite: %v", err)
	}

	defer func() {
		err := client.Close()
		if err != nil {
			log.Fatalf("failed to close client")
		}
	}()

	// Run the auto migration tool.
	if err := client.Schema.Create(context.Background()); err != nil {
		log.Fatalf("failed creating schema resources: %v", err)
	}

	u, err := CreateUser(ctx, client)
	if err != nil {
		log.Fatalf("called CreateUser(), got error: %v", err)
	}
	log.Println(u)
}
```

- run `go run main.go`

At this point I'd expect it to either print out the created user or error out somehow. But it doesn't. `go run main.go` just keeps running infinitely, no console output or errors or anything. I opened the postgres table in pgadmin4 and the schema was created correctly but the user row didn't get created. Same thing happens with sqlite. Go version go1.15.5 darwin/amd64 if that matters.

**Comment by adrianocr** [comment]
OK I found the issue. 

`var ctx context.Context` is incorrect. It should be `ctx := context.Background()` and the issue goes away. Ideally ent should error out on the wrong context usage but it does not.

**Comment by giautm** [comment]
Ent can't check context is correct or not, that caused by design of context module.
