### ISSUE TITLE
Add support for additional fields in Connection objects

### ISSUE THREAD

**Issue by dilipkk-foyernet** [facebook/ent#1009]
Hi @a8m, 

We need to add additional fields to generated connect objects by pagination template.
https://github.com/facebookincubator/ent-contrib/blob/master/entgql/template/pagination.tmpl

```go
{{/* A template for adding additional fields to specific types. */}}
{{ define "model/fields/additional" }}
    {{- /* Add static fields to the "Card" entity. */}}
    {{- if eq $.Name "Card" }}
        // StaticField defined by templates.
        StaticField string `json:"static_field,omitempty"`
    {{- end }}
{{ end }}
```
Just like above if you can add support to override a template to add more fields to the connections object then it will help us to extend them as per our needs.

Thanks,
Dilip

**Comment by dilipkk-foyernet** [comment]
Solved using a different approach so this is not needed at this moment.

**Comment by a8m** [comment]
Great @dilipkk-foyernet.

Feel free to share your workaround for future readers. Thanks 😊

**Comment by dilipkk-foyernet** [comment]
```go
// DeviceConnection is for constructing device search response
type DeviceConnection struct {
	*ent.DeviceConnection
	CountByType []*DeviceCountByType
}
```
I am extending ent connection object and adding custom fields.

**Comment by dilipkk-foyernet** [comment]
@a8m if you have time then can you tell me what I am doing wrong here: https://github.com/facebookincubator/ent-contrib/pull/19, just for my understanding.
