### ISSUE TITLE
IsInt returns false on custom ID field

### ISSUE THREAD

**Issue by masseelch** [facebook/ent#1010]
If i define my schema like this to add some struct tags:
```go
// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id").
			StructTag(`groups:"user:list,auth:login"`),
}
```

Calling [`IsInt`](https://pkg.go.dev/github.com/facebook/ent/entc/gen#Field.IsInt) on the [`Type.ID`](https://pkg.go.dev/github.com/facebook/ent/entc/gen#Type) will return false.

**Comment by a8m** [comment]
Hey @masseelch,
Please feel free to send a patch to fix it, or I can look at it later.

Thanks 🙃

**Comment by masseelch** [comment]
I'll try to dig in tomorrow

**Comment by masseelch** [comment]
Looks like current master does not have this problem any more. 

I added a test regarding this though. Do you want a PR for that one? Might prevent a regression.

**Comment by masseelch** [comment]
I'll close. Please contact me if you are interested in the test.

**Comment by a8m** [comment]
Hey @masseelch, sorry for the delayed response. 

Feel free to send a patch and I’ll look at this later. Thanks 🙏🏻
