### ISSUE TITLE
Convert date after query

### ISSUE THREAD

**Issue by samuelralmeida** [facebook/ent#1012]
Hi guys, 

we have a database in local time zone, so when we execute a query to get data, time fields return in this local time zone.

I want to create some way in the schema description to "tell to `ent`": every time that you do a query from this entity, call a function to convert time zone. It would look like a unmarshal function.

I've tried somethings but nothing works. Is it possible? Can someone help me?

Thanks!

**Comment by a8m** [comment]
Hey @samuelralmeida,
I'll look at this in more details tomorrow morning (related to https://github.com/facebook/ent/issues/833).

**Comment by a8m** [comment]
Hey @samuelralmeida and sorry for the delayed response.

Regarding your issue, can you elaborate please on what database/driver do you use with ent? Some drivers support this already (e.g. [MySQL driver](https://github.com/go-sql-driver/mysql#loc)).

Other approach is to use your [own type](https://entgo.io/docs/schema-fields/#go-type) and implement the [`sql.Scanner`](https://golang.org/pkg/database/sql/#Scanner) interface.

**Comment by samuelralmeida** [comment]
> Hey @samuelralmeida and sorry for the delayed response.
> 
> Regarding your issue, can you elaborate please on what database/driver do you use with ent? Some drivers support this already (e.g. [MySQL driver](https://github.com/go-sql-driver/mysql#loc)).
> 
> Other approach is to use your [own type](https://entgo.io/docs/schema-fields/#go-type) and implement the [`sql.Scanner`](https://golang.org/pkg/database/sql/#Scanner) interface.

@a8m, it works. Thanks a lot!

**Comment by a8m** [comment]
Wonderful! Thanks for raising up this issue, and you're welcome to join our slack channel - https://gophers.slack.com/archives/C01FMSQDT53
