### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by pjebs** [facebook/ent#1025]
If the primary aim is to make an API that performs as fast as possible, and I have the choice of using ent (with postgres) or standard relationships using foreign keys etc in tables on postgres, would ent be significantly slower.

The schema is not super heavy with relationships everywhere.

**Comment by a8m** [comment]
Hey @pjebs and thanks for raising up this question.

> and I have the choice of using ent (with postgres) or standard relationships using foreign keys etc in tables on postgres

The framework uses the standard and the common data modelling for its relationships (i.e. tables and foreign-keys).

For O2M/M2O and O2O relationships/edges it uses FKs on the table creation and for M2M relationships/edges it creates a join table for the association.

You're welcome to share you schema here and I can elaborate on your specific use case.

**Comment by pjebs** [comment]
@latysh

**Comment by a8m** [comment]
Closing, since there are no further comments. 
Feel free to continue the discussion or reopen the issue if it's needed.
