### ISSUE TITLE
entgql: edge was not loaded after mutation

### ISSUE THREAD

**Issue by giautm** [facebook/ent#1026]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Returns GraphQL errors:
```json
{
  "errors": [
    {
      "message": "ent: parent edge was not loaded",
      "path": [
        "createTodo",
        "parent"
      ]
    }
  ],
  "data": null
}
```

## Expected Behavior 🤔

Return parent of created todo:

```json
{
  "data": {
    "createTodo": {
      "id": "2",
      "parent": {
        "id": "1",
        "text": "Parent Todo"
      },
      "text": "OKE",
      "status": "IN_PROGRESS"
    }
  }
}
```
## Steps to Reproduce 🕹

https://github.com/giautm/entgo-todo

Steps:

1. go run ./server/
2. Create first todo:
```gql
mutation {
  createTodo(todo: {
    text: "Parent Todo"
  }) {
    id
    text
    status
  }
}
```
3. Create second todo with parent
```gql
# Write your query or mutation here
mutation {
  createTodo(todo: {
    text: "OKE"
    parent: 1
  }) {
    id
    parent {
      id
      text
    }
    text
    status
  }
}
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.15.4  |
| Ent         | 0.5.?   |

**Comment by alexsn** [comment]
Hi @giautm, I assume your example is based on ent-contrib/todo package. The seen behavior is caused by the fact that edges are _not_ eagerly loaded on mutation but the resolver tried to return them as such. I've updated the todo example to fallback to a edge query in such a case (see https://github.com/facebookincubator/ent-contrib/commit/1825b356fd5aedf482b07c2209a670f0f706b7f0).

**Comment by giautm** [comment]
Yep, It based on `ent-contrib/todo` package. I applied your patch and it work fine. However, I think the code gen should handle this case, rather manually update for every resolver. Do you think like that?

**Comment by alexsn** [comment]
It's possible in theory but not trivial as:
- Eager loading is not supported (not does it make sense) on mutation.
- Mutation resolver are _not_ generated (`CreateTodo` being one).

Feel free to give it a shot but it's rather complicated and not something we plan to implement in the near future.

**Comment by giautm** [comment]
It helpful to reduce boilerplate code.

```go
func (r *channelResolver) Conversation(ctx context.Context, obj *entv1.Channel) (*entv1.Conversation, error) {
	conv, err := obj.Edges.ConversationOrErr()
	if entv1.IsNotLoaded(err) {
		conv, err = obj.QueryConversation().Only(ctx)
	}
	return conv, err
}

func (r *messageResolver) Conversation(ctx context.Context, obj *entv1.Message) (*entv1.Conversation, error) {
	conv, err := obj.Edges.ConversationOrErr()
	if entv1.IsNotLoaded(err) {
		conv, err = obj.QueryConversation().Only(ctx)
	}
	return conv, err
}

func (r *messageResolver) Thread(ctx context.Context, obj *entv1.Message) (*entv1.Conversation, error) {
	thread, err := obj.Edges.ThreadOrErr()
	return thread, entv1.MaskNotFound(err)
}
```

**Comment by alexsn** [comment]
Yes, I agree that this boilerplate should be reduced. See https://github.com/facebookincubator/ent-contrib/commit/113724014b2f77fa69e627a0d768f4404cf39c28 which removed the need for those resolvers in the first place.

**Comment by giautm** [comment]
Hi, thank you very much!
