### ISSUE TITLE
Add OneOrNone Query Method

### ISSUE THREAD

**Issue by cliedeman** [facebook/ent#1027]
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

```go
usr, err := client.User.Query().Where(...).OneOrNone(ctx)

if err != nil {
  return nil, err
}
```

## Motivation 🔦

To query for a single record or none the best we can currently do is

```go
usr, err := client.User.Query().Where(...).Only(ctx)

if err != nil && !ent.IsNotFound(err) {
  return nil, err
}
```

`First` could work but it does not perform the non singular check

OneOrNone is not a great name but I could not think of a better one
* One (Too simliar to Only)
* OneOrNil
* FirstOne

Example Implementation

```
func (uq *UserQuery) OneOrNone(ctx context.Context) (*User, error) {
	nodes, err := uq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
                 return nil, nil
	default:
		return nil, &NotSingularError{user.Label}
	}
}
```

# Related 
- https://github.com/facebook/ent/issues/849#issuecomment-709508849

**Comment by giautm** [comment]
I voted for OneOrNil.

**Comment by alexsn** [comment]
This can be achieved with a combination of `Only` / `MaskNotFound` as follows:
```go
usr, err := client.User.Query().Where(...).Only(ctx)
if err = ent.MaskNotFound(err); err != nil {
    return nil, err
}
```
So I don't think the above is needed. You can of course add the above functionality to your project using custom templates.

**Comment by cliedeman** [comment]
Hi @alexsn

I want to make the argument this should be in the default templates because I think it will be useful in all projects.

**Comment by alexsn** [comment]
I think our preference is to keep the API small (to avoid confusion) and I see little value in adding a helper that combines `Only` + `MaskNotFound`.

**Comment by a8m** [comment]
Thanks or proposing this @cliedeman.

I tend to agree with @alexsn, especially because I'm working atm on moving stuff to feature-flags to make the base codegen assets much smaller.

Regarding this new API, since it doesn't require any runtime-specific logic, I think it's better to create a plugin for it in a different repo for now (and maybe mentioning it in our website) and possibly adding it to the core features if we'll see a big adoption for this.

I encourage our internal users to go through the same process as well. They start with custom templates for such proposals and we consider adding them to the framework only after we have some experience with it - because once you add it, you can't never go back.

**Comment by ORBAT** [comment]
Just food for thought, but I've found the "not found is not an error" API design pattern to produce cleaner code; the idea is to only return an error if something actually went wrong with a query, so eg. not finding any users named "Bob" isn't an error and would just return `nil, nil` (of course in some contexts not finding something _is_ an error.) Just like the standard functional `list.filter( x => x.name == "Bob")` wouldn't throw an exception if it returned no results.

The idea is that errors are about something exceptional that shouldn't happen during normal operation, that way you avoid having to inspect every error to see if it was really an error or not.

**Comment by aight8** [comment]
#870  #"Error Handling"

**Comment by giautm** [comment]
In most cases, we need to check `err != nil` before do anything with the entity (also not nil). So, we don't need to use `MaskNotFound` for this cases.

`ent.MaskNotFound()`, still have positive value. When we integrate with `gqlgen` to return nullable field for the resolver. It very special for GraphQL, we can reduce by provide custom template. Idea is generate custom resolve by using Annotations config `entgql.Resolver()`; this annotations will check the field is nullable or not then auto using MaskNotFound for the field's resolver.

**Comment by cliedeman** [comment]
Thanks for all the feedback. I updated the original issue with some prior art and a bit more explanation of the different query styles.

This can easily be added to the api via a custom template so I think this can be closed.

Ciaran

**Comment by alexsn** [comment]
While we're on this topic I really don't see the point of having `First` query finisher. Anyone actually using it? If so can you provide a use case?

**Comment by a8m** [comment]
> Anyone actually using it? If so can you provide a use case?

I'm using it. Getting the first value by some ordering (max, min, etc).
