### ISSUE TITLE
entgql: How to return Relay's edge for new created node.

### ISSUE THREAD

**Issue by giautm** [facebook/ent#1034]
As [Relay spec](https://relay.dev/docs/en/mutations#range_add) for create in new edge, we need to return `MessageEdge`. But, the Cursor field currently depend on `OrderField`. And there is no method for creating new `MessageEdge` by hand.

```gql
type SendMessagePayload {
  messageEdge: MessageEdge!
}

type Mutation {
  sendMessage(conversationID: ID!, msg: MessageInput!): SendMessagePayload!
}
```

currently, I use bellow code. But It don't feel right.

```golang
	node, err := client.Message.Create().
		SetAuthor(auth).
		SetText(msg.Text).
		SetConversationID(conversationID).
		Save(ctx)

	return &model.SendMessagePayload{
		MessageEdge: &entv1.MessageEdge{
			Node: node,
			Cursor: entv1.Cursor{
				ID: node.ID,
				// What is Value?
				Value: nil,
			},
		},
	}, nil
}
```

**Comment by a8m** [comment]
Hey @giautm!

> And there is no method for creating new MessageEdge by hand.
> ...
> currently, I use bellow code. But It don't feel right.



Can you elaborate please? Or give more details how do you expect the API to look like?

**Comment by giautm** [comment]
Hi, @a8m. I want to return new edge after add new node to connection, following Relay spec. So, I want to know how to do that with gqlgen and entgo?.

So, Can I write some code like above? What is Value in Cursor?
```golang
func NewMessageEdge(node *entv1.Message) *entv1.MessageEdge {
	return &entv1.MessageEdge{
		Node: node,
		Cursor: entv1.Cursor{
			ID: node.ID,
			// What is Value?
			Value: nil,
		},
	}
}
```

Some generated code related to `Cursor`; but I can't call `toCursor` because it's private
```golang
	// MessageOrderFieldTimestamp orders Message by timestamp.
	MessageOrderFieldTimestamp = &MessageOrderField{
		field: message.FieldTimestamp,
		toCursor: func(m *Message) Cursor {
			return Cursor{
				ID:    m.ID,
				Value: m.Timestamp,
			}
		},
	}
```

**Comment by alexsn** [comment]
Hi @giautm, a relay `Cursor` only makes sense when using pagination (iterating over pages) so I'm not sure why you'd want to get a edge with a cursor back from a mutation? Can you post the mutation you're trying to invoke on the client side and explain the logic behind it?

Now when it comes to the cursor it encodes the `ID` of the object and the `Value` of the field you're ordering by so we'll know how to retrieve the next page given a cursor and edge ordering. If the `Value` is nil it's assumed your ordering by the `ID` field. You're not suppose to construct cursors manually but that's the logic they encode if you want to do so manually.

Lastly this type of issues should be posted on [ent-contrib](https://github.com/facebookincubator/ent-contrib) is this has nothing to do with ent itself.

**Comment by giautm** [comment]
Hi, entgql was not enable to post issue. So I have to post to ent.

My Mutation follow Relay desc spec as here: https://relay.dev/docs/en/mutations#range_add

**Comment by a8m** [comment]
I will enable the issue tracker for ent-contrib.

**Comment by alexsn** [comment]
> Hi, entgql was not enable to post issue. So I have to post to ent.
> 
> My Mutation follow Relay desc spec as here: https://relay.dev/docs/en/mutations#range_add

This is an API Reference and not a spec and my above comment explains how you can construct a cursor.

**Comment by giautm** [comment]
Tks @alexsn, can we export toCusor from OrderField? So I can use order field to construct Cursor for edge.

**Comment by alexsn** [comment]
> Tks @alexsn, can we export toCusor from OrderField? So I can use order field to construct Cursor for edge.

I rather not, you can manually fill the fields as described above.

**Comment by giautm** [comment]
Okay, I will use custom template to generate `NewMessageEdge`. When create new message, client must provide current order to construct Edge to allow Relay append new Edge to current Connection in client cache.

```go
func NewMessageEdge(node *Message, order *MessageOrder) *MessageEdge {
	if order == nil {
		order = DefaultMessageOrder
	}

	return &MessageEdge{
		Node:   node,
		Cursor: order.Field.toCursor(node),
	}
}
```

And update GraphQL mutation to:
```gql
type SendMessagePayload {
  messageEdge: MessageEdge!
}

type Mutation {
  sendMessage(conversationID: ID!, msg: MessageInput!, orderBy: MessageOrder): SendMessagePayload!
}
```

Mutation implement:
```go
func (r *mutationResolver) SendMessage(ctx context.Context, conversationID int, msg model.MessageInput, orderBy *entv1.MessageOrder) (*model.SendMessagePayload, error) {
	client := entv1.FromContext(ctx)

	//...

	node, err := client.Message.Create().
		SetAuthor(auth).
		SetText(msg.Text).
		SetConversationID(conversationID).
		Save(ctx)

	return &model.SendMessagePayload{
		MessageEdge: entv1.NewMessageEdge(node, orderBy),
	}, nil
}
```

**Comment by giautm** [comment]
I sent PR for this, You can merge if interested https://github.com/facebookincubator/ent-contrib/pull/24
