### ISSUE TITLE
How to use foreign keys as search criteria alone？

### ISSUE THREAD

**Issue by G-Bruin** [facebook/ent#1049]
**cars table**
![image](https://user-images.githubusercontent.com/20853074/102292815-deb99480-3f80-11eb-8782-55ece9c5d8f9.png)

**users table**

![image](https://user-images.githubusercontent.com/20853074/102292842-ebd68380-3f80-11eb-809f-56c4d8a8c6a7.png)

**i want to use sql like this**
```
 `select * from cars where user_cars = '1liZXnlx85PAjpF5rsaAH6qDA7v' `
```
**the `user_cars` as  search criteria， What should I do with it？**

**Comment by a8m** [comment]
Hey @G-Bruin,
If you don't want to use the `Has<E>With(...)` predicates, you can use a custom one for writing such queries.
See https://entgo.io/docs/predicates/#custom-predicates

**Comment by G-Bruin** [comment]
Hey @a8m，
when I use sql
```
select * from cars
```
like this:
```
cars, err := peanut_pg.QueryCars().All(ctx)
if err != nil {
    return fmt.Errorf("failed querying user cars: %v", err)
}
log.Println("returned cars:", cars)
```
![image](https://user-images.githubusercontent.com/20853074/102330024-0716b280-3fc4-11eb-985f-055677bc6b13.png)

Why is there no **user_cars** field？

**Comment by a8m** [comment]
It should be added soon. See https://github.com/facebook/ent/pull/1046

**Comment by G-Bruin** [comment]
@a8m thx

**Comment by a8m** [comment]
Great, closing 😃
