### ISSUE TITLE
mixin: share type when use mixin for schema

### ISSUE THREAD

**Issue by giautm** [facebook/ent#1055]
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I want to share an Enum cross entities, so I created a mixin as `ConfirmMixin` as follow:

```golang
// ConfirmMixin implements the ent.Mixin for sharing
// confirm with package schemas.
type ConfirmMixin struct {
	mixin.Schema
}

func (ConfirmMixin) Fields() []ent.Field {
	return []ent.Field{
		field.Enum("confirm_status").
			Values("confirm", "decline").
			Optional(),
	}
}
```

then, use it in schema defination:

```golang
func (JobApplication) Mixin() []ent.Mixin {
	return []ent.Mixin{
		ConfirmMixin{},
	}
}
```
```golang
func (ShiftShowUp) Mixin() []ent.Mixin {
	return []ent.Mixin{
		ConfirmMixin{},
	}
}
```

Currently, ent generate both `jobapplication.ConfirmStatus` and `shiftshowup.ConfirmStatus` with exactly same.

## Motivation 🔦

I wish ent generate a single type for ConfirmStatus and share it cross entities.

**Comment by a8m** [comment]
Hey @giautm,
You can use the [GoType](https://entgo.io/docs/schema-fields/#go-type) option to create your own type, and share it with multiple schemas.

**Comment by giautm** [comment]
Yup, but I will lost validation logic that ent ready generated. :p

**Comment by a8m** [comment]
It should enforce validation as well. See a usage example - 
https://github.com/facebook/ent/blob/master/entc/integration/ent/schema/fieldtype.go#L132
https://github.com/facebook/ent/blob/master/entc/integration/ent/role/role.go

**Comment by giautm** [comment]
Nice, It work as expected.

**Comment by giautm** [comment]
btw, I think this line should convert to `role.Read`. Because "role" is not valid value and it make confusing
 https://github.com/facebook/ent/blob/3daea98d76a3200f8e9f5727fdbf864e1caa0abb/entc/integration/ent/schema/fieldtype.go#L134

```golang
			GoType(role.Read),
```

**Comment by giautm** [comment]
Hi @a8m , I open an issue for new bug: https://github.com/facebook/ent/issues/1056

**Comment by a8m** [comment]
> btw, I think this line should convert to `role.Read`. Because "role" is not valid value and it make confusing
> 
> https://github.com/facebook/ent/blob/3daea98d76a3200f8e9f5727fdbf864e1caa0abb/entc/integration/ent/schema/fieldtype.go#L134
> 
> ```go
> 			GoType(role.Read),
> ```

Feel free to send a patch for fixing this. Thanks
