### ISSUE TITLE
Support for custom json struct tag naming strategy. 

### ISSUE THREAD

**Issue by notzheng** [facebook/ent#1069]
Now, the generated json struct tag uses the field name. Hope to support customization, such as the camelcase form of field name.

- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

For Example, I have defined a schema

```golang
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id").
			Positive(),
		field.String("username"),
		field.String("follower_count"),
		field.String("password").
			Sensitive(),
	}
}
```

And it generate the struct like this

```golang

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// FollowerCount holds the value of the "follower_count" field.
	FollowerCount string `json:"follower_count,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"-"`
}
```
If I want to turn the  json tag of `FollowerCount` field into a camelcase, I have to do this

```golang
field.String("follower_count").StructTag("json:\"followerCount,omitempty\""),
```

This is fine if there are only a few fields, but it is cumbersome to do this for many fields in many tables.

So is it possible to provide a configuration here that allows you to choose the naming strategy for the generated json tag?

## Motivation 🔦

In most cases, we will choose the snake case form in the naming of the database fields, and the camelcase in the Api.

**Comment by notzheng** [comment]
Oh, I just found out I can do this
```golang
  field.String("followerCount").StorageKey("follow_count")
```
This is indeed simpler and clearer.

**Comment by a8m** [comment]
Hey @notzheng and thanks for proposing this option.

Like you mentioned, you can use the `StructTag` (or `StorageKey`) explicitly on each field to configure these options.
However, if users want to an elegant way to enforce custom naming on all fields, they can just write a helper function for adding this for them. For example, imagine write your schema as follows:

```go
func (User) Fields() []ent.Field {
	return fieldtag.Snaked(
		field.Int("id").
			Positive(),
		field.String("username"),
		field.String("follower_count"),
		field.String("password").
			Sensitive(),
	)
}
```

We have similar functions for configuring all fields/edges in the schema both internally and in ent (see, [mixin example](https://github.com/facebook/ent/blob/master/schema/mixin/mixin.go)).

**Comment by notzheng** [comment]
> Hey @notzheng and thanks for proposing this option.
> 
> Like you mentioned, you can use the `StructTag` (or `StorageKey`) explicitly on each field to configure these options.
> However, if users want to an elegant way to enforce custom naming on all fields, they can just write a helper function for adding this for them. For example, imagine write your schema as follows:
> 
> ```go
> func (User) Fields() []ent.Field {
> 	return fieldtag.Snaked(
> 		field.Int("id").
> 			Positive(),
> 		field.String("username"),
> 		field.String("follower_count"),
> 		field.String("password").
> 			Sensitive(),
> 	)
> }
> ```
> 
> We have similar functions for configuring all fields/edges in the schema both internally and in ent (see, [mixin example](https://github.com/facebook/ent/blob/master/schema/mixin/mixin.go)).

Thank you very much, it solved my problem perfectly, I will close this issue.

**Comment by a8m** [comment]
Sure, glad to help!

**Comment by Locter9001** [comment]
So where is the implementation of the `fieldtag.Snaked` function? I don't find it in the `mixin example` you gave me because 
```go
type Field interface {
    Descriptor() *Descriptor
}
```
is an interface, how do I modify his tag and will I get an error if I do it directly?

**Comment by Locter9001** [comment]
@notzheng

**Comment by Locter9001** [comment]
my code
```go
func GenerateStructTag(fields ...ent.Field) []ent.Field {
	for _, f := range fields {
		if !f.Descriptor().Sensitive {
			if strings.HasSuffix(f.Descriptor().Comment, "[hide]") {
				f.Descriptor().Tag = `json:"-"`
			} else {
				f.Descriptor().Tag = fmt.Sprintf(`json:"%s"`, f.Descriptor().Name)
			}
		}
	}

	return fields
}
```

**Comment by khanakia** [comment]
@Locter9001 where did you add the code?

I want all the JSON tags to be camelcase not snake case

**Comment by a8m** [comment]
A long time has passed since my previous comment. You can now use codegen hooks to customize this. See: https://entgo.io/docs/code-gen/#code-generation-hooks

**Comment by khanakia** [comment]
Hook runs after the structs are generated already e.g. EnsureStructTag 

But I need to override the schema before it generates the code actually so I can add custom JSON annotations

**Comment by a8m** [comment]
Codegen hooks are similar to schema/runtime hooks. You can add code before assets are written, and after it (`next.Generate(…)`).

**Comment by khanakia** [comment]
Ok i was able to override but is there a way to preserve existing struct tag which are not json e.g. `gqlgen:test`
```go
// convert ent snake_case json tags to camelCase for all the schema fields automatically
func FieldSnakeToCamel() gen.Hook {
	return func(next gen.Generator) gen.Generator {
		return gen.GenerateFunc(func(g *gen.Graph) error {
			for _, node := range g.Nodes {
				for _, field := range node.Fields {
					field.StructTag = `json:"` + strcase.ToLowerCamel(field.Name) + `,omitempty"`
				}
			}
			return next.Generate(g)
		})
	}
}
```

**Comment by a8m** [comment]
You can utilize the reflect package to manipulate struct-tag strings. For example: https://github.com/ent/ent/blob/master/entc/gen/type.go#L2190
