### ISSUE TITLE
Cant make a defined PK not autoincremental

### ISSUE THREAD

**Issue by saantiaguilera** [facebook/ent#1073]
We have an entity that doesn't define itself its PK (we already have it from another service, we just store it alongside some information). For reference let's say we have a User with a driver_id(PK int) + name(string) (but the ID already exists in another service)

We are building the fields like this:
```go
return []ent.Field{
  field.Int("id").Immutable().Unique().StorageKey("driver_id"),
  // other fields
}
```
Yet, when we run Ent and see the schema creation query, it makes it autoincremental (when it shouldn't be, since we already know it and we will provide it when creating)

Query looks like this (not pasting it completely as it includes other non relevant info:
```
BEGIN;
CREATE TABLE `user`(`driver_id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, ...
```

Is there a way to avoid having a useless PK (which will be autoincremental but not the PK we want), and making our own "external" integer our PK? (being non autoincremental)

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Trying to make our own PK makes it autoincremental when we don't specify it (nor we can avoid it)

## Expected Behavior 🤔

We should be able to specify it or at least disable it.

## Steps to Reproduce 🕹

1. ent init User
2. Create a field as the above
3. Generate code and see the table schema creation

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.14  |
| Ent         | 0.5.3   |
| Database    | sqlite3   |

**Comment by a8m** [comment]
Hey @saantiaguilera and thanks for raising up this issue. 
It's actually a duplicate of https://github.com/facebook/ent/issues/559, and we can address it if it's needed. Let's continue the discussion there?

**Comment by saantiaguilera** [comment]
Sure! Closing this. Thanks!
