### ISSUE TITLE
Can't insert a date below 31 December 1969.

### ISSUE THREAD

**Issue by synt8x** [facebook/ent#1076]
I'm building a web application that needs to store a birth_date but when trying to insert a birth_date less than 31 December 1969? Does anyone know how to fix it?

**Comment by a8m** [comment]
Hey @synt8x, can you please provide more details on your environment? (e.g. database version)

**Comment by synt8x** [comment]
As database I use AWS Aurora/MySQL with MySQL version 5.6.
When I try to insert the following to my db using ent: `1969-01-01 12:00:00 +0000 UTC` it inserts this `0000-00-00 00:00:00`

**Comment by synt8x** [comment]
Got the same error when inserting this `1969-01-01 06:00:00 +0100 CET`

**Comment by a8m** [comment]
Thanks for the details. `Time` fields use the MySQL `TIMESTAMP` type in the schema creation by default, and this type has a has a range of '1970-01-01 00:00:01' UTC to '2038-01-19 03:14:07' UTC (see, [MySQL docs](https://dev.mysql.com/doc/refman/5.6/en/datetime.html)). 

If you want a wider range, use the MySQL `DATETIME` instead using the [SchemaType](https://entgo.io/docs/schema-fields/#database-type) option. For example:
```go
field.Time("birth_date").
	Optional().
	SchemaType(map[string]string{
		dialect.MySQL:    "datetime",
		dialect.Postgres: "date",
	}),
```

**Comment by synt8x** [comment]
Thanks man you made my day :)

**Comment by a8m** [comment]
Sure, let me know if you still have troubles with it.
