### ISSUE TITLE
dialect/sql Selector Query

### ISSUE THREAD

**Issue by maxiloEmmmm** [facebook/ent#1081]
```go
func TestEntQuery(t *testing.T) {
	table := sql.Select().From(sql.Table("x")).As("q").Where(sql.EQ("A", 1))
	q1, _ := table.Query()
        // table.where Predicate cached
	q2, _ := table.Query()
	require.Equal(t, q2, q1)
}
```

```shell
Expected :SELECT * FROM `x` WHERE `A` = ?`A` = ?
Actual   :SELECT * FROM `x` WHERE `A` = ?
```

i know can use 
```go
table.Query().Clone()
``` 
but i need to resolve some func
```go
func Test(sel *sql.Selector, start int, size int) {
  sql.Select("count(1)").From(sel).Query()
  sel.Limit(size).Offset(int).Query()
  // t1 can't Clone in there, will where duplicate
}

t1 := sel.Where(sql.EQ("a", 1))
sel = sql.Select().From(t1)
Test(sel, 1, 10)
```

## i do this
https://github.com/facebook/ent/blob/08d2cd797d177afb9b236cf021e26b4b5092e791/dialect/sql/builder.go#L1814
to
```go
b.Join(join.on.clone())
```
and
https://github.com/facebook/ent/blob/08d2cd797d177afb9b236cf021e26b4b5092e791/dialect/sql/builder.go#L1819
to
```go
b.Join(s.where.clone())
```
it's can resolve my question

Q: Is there any other way?

**Comment by a8m** [comment]
Hey @maxiloEmmmm! It's great to see you here again 😃 
Thanks for reporting this. I'll give it a look.

**Comment by a8m** [comment]
https://github.com/facebook/ent/pull/1092 solves the issue, feel free to update to latest master

```console
go get github.com/facebook/ent@master
```

**Comment by maxiloEmmmm** [comment]
@a8m thk
