### ISSUE TITLE
Should I exclude the files generated by entc from vcs?

### ISSUE THREAD

**Issue by YianAndCode** [facebook/ent#1082]
After execute `go generate ./ent`, there are lots of files generated.

Should I exclude these files from vcs? Such as put the content below to `./ent/.gitignore`
```
*
!generate.go
!schema/
```

Or keep them in vcs？

Which is best practice?

**Comment by a8m** [comment]
Hey @YianAndCode,
I'm not aware on any best practice, but from my experience, it's pretty common (in Go) to keep the generated assets in VCS. Not only for ent, but for other projects as well (e.g. gqlgen, protobuf, go-swagger, etc).

GitHub PR diff works with it really well BTW.

**Comment by YianAndCode** [comment]
Hi @a8m,
I got it, thank you very much!
