### ISSUE TITLE
Select fields in O2M type not working well

### ISSUE THREAD

**Issue by katiestone** [facebook/ent#1089]
So i have a entity patent and other entities like patentTitle etc which belong to patent. Now i want to select some fields of patent and some fileds of patentTitle which is related to that patent i select. I wrote the query as below,
```go
err := p.client.Patent.Query().Where(patent.IDIn(req.IDs...)).WithPatentTitles(func(q *ent.PatentTitleQuery) {
		q.Limit(5)
		q.Select(patenttitle.FieldID, []string{"title"}...)
	}).Select(patent.FieldID, p.ctx.Fields...).Scan(p.ctx, &result)
```
but it turned out that only patent can be queried, the edges property of this patent was null. so i changed the query as below, 
```go
result, err := p.client.Patent.Query().Where(patent.IDIn(req.IDs...)).WithPatentTitles(func(q *ent.PatentTitleQuery) {
		q.Limit(5)
		q.Select(patenttitle.FieldID, []string{"title"}...)
	}).All(p.ctx)
```
then the edges property came out, but all of the fields of patentTitle has been selected, seems that the select fun in WithPatentTitles fun didin't work. 
So my question is how can i make both selection work? one on patent one on patentTitle
thank you

**Comment by a8m** [comment]
Hey @katiestone and thanks for reporting this issue.

#1094 should solve this problem, and you can update to latest master as follows:

```console
go get github.com/facebook/ent@master
```

BTW, use ```go for formatting codeblocks in GitHub issues/comments (see, [GitHub markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown)).

**Comment by katiestone** [comment]
Hey @a8m thanks for your help, i've tried it today, but it seems there is still some problem, it works when i wrote a query as below,
```go
p.client.Debug().Patent.Query().Where(patent.IDIn(req.IDs...)).WithPatentTitles(func(query *ent.PatentTitleQuery) {
		query.Select(patent.FieldID, "title").Scan(p.ctx, &patentTitle)
	}).All(p.ctx)
```
so the results include all fields of patent and field 'title' of patentTitle, but when i want to use the selection on both entities as below,
```go
p.client.Debug().Patent.Query().Where(patent.IDIn(req.IDs...)).WithPatentTitles(func(query *ent.PatentTitleQuery) {
		query.Select(patent.FieldID, "title").Scan(p.ctx, &patentTitle)
	}).Select(patent.FieldID, p.ctx.Fields...).Scan(p.ctx, &result)
```
the 'PatentTitles' property in 'Edges' property of the result was nil
![image](https://user-images.githubusercontent.com/26614324/103256321-cce7e080-49c7-11eb-9818-5c373f6629b2.png)
not it seems like only one select func works, either on patent or patenttile

**Comment by katiestone** [comment]
> Hey @a8m thanks for your help, i've tried it today, but it seems there is still some problem, it works when i wrote a query as below,
> 
> ```go
> p.client.Debug().Patent.Query().Where(patent.IDIn(req.IDs...)).WithPatentTitles(func(query *ent.PatentTitleQuery) {
> 		query.Select(patent.FieldID, "title").Scan(p.ctx, &patentTitle)
> 	}).All(p.ctx)
> ```
> 
> ![image](https://user-images.githubusercontent.com/26614324/103256691-1be24580-49c9-11eb-862e-c5525c1b31da.png)
> 
> so the results include all fields of patent and field 'title' of patentTitle, but when i want to use the selection on both entities as below,
> 
> ```go
> p.client.Debug().Patent.Query().Where(patent.IDIn(req.IDs...)).WithPatentTitles(func(query *ent.PatentTitleQuery) {
> 		query.Select(patent.FieldID, "title").Scan(p.ctx, &patentTitle)
> 	}).Select(patent.FieldID, p.ctx.Fields...).Scan(p.ctx, &result)
> ```
> 
> the 'PatentTitles' property in 'Edges' property of the result was nil
> ![image](https://user-images.githubusercontent.com/26614324/103256321-cce7e080-49c7-11eb-9818-5c373f6629b2.png)
> not it seems like only one select func works, either on patent or patenttile

problem solved, instead of using 'Scan()', i need to use 'All()' after "Slect()'

**Comment by a8m** [comment]
You're right. The `Scan` method doesn't work with eager-loading. Use `All` instead and ent will query any fill only the fields you selected (and the ID field of course). 

Closing, but you're welcome to contribute a documentation change if you find the docs/examples confusing or missing information. Thanks!
