### ISSUE TITLE
How can I make array field ?

### ISSUE THREAD

**Issue by ducnguyen96** [facebook/ent#1090]
I have an enum like this:
```go
enum RoleEnum {
	SUPER_ADMIN
	ADMIN
	BUYER
	SELLER
	POWER_SELLER
	PARTNER	
}
```

I want to implement a field with type []RoleEnum, another field with type []Uint64. How can I do ?

```go
// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Uint64("id").Positive(),
		field.String("name").
			Unique().
			NotEmpty(),
		field.String("avatar").
			Optional(),
		field.String("description").
			Optional(),
                // field.Enums("roles")
                // field.Unint64s("shopIds")
	}
}
```

Typescript + typeorm implement:
```typescript
@Column({ type: 'enum', array: true, enum: RoleEnum, name: "roles })
roles: RoleEnum[];

@Column({ array: true, name: "shop_ids" })
shopIds: bigint[];
```

**Comment by ducnguyen96** [comment]
Do I need to convert them all to strings ?

**Comment by a8m** [comment]
Hello @ducnguyen96,

> Do I need to convert them all to strings ?

No. The `field` package provides multiple list builders like `field.Strings` and `field.Ints`, but they're actually implemented using the JSON type. Thus, if you want to have an arbitrary type (which is convertible to JSON), you can define it as follows:

```go
field.JSON("roles", []Role{}),
field.JSON("shop_ids", []uint64{}),
```  
Then, in the generated API you'll interact with `[]uint64` and `[]Role` - the framework does all encode/decode magic for you. 
For predicates support, see [sqljson](https://pkg.go.dev/github.com/facebook/ent/dialect/sql/sqljson) and [custom predicates](https://entgo.io/docs/predicates/#custom-predicates).

**Comment by a8m** [comment]
Closing, but feel free to continue the discussion or re-open it if something doesn't work for you.
