### ISSUE TITLE
ent with embedded cache

### ISSUE THREAD

**Issue by daginwu** [facebook/ent#1113]
ent with embedded cache

hey, developers i think integrating all data model with embedded cache (such as "groupcache") is a good idea !

- [ ] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

**Comment by a8m** [comment]
Hey @daginwu and thanks for the proposal.
Caching is definitely something that I want to add to ent. 

Closing as this duplication of https://github.com/facebook/ent/issues/958 😃
