### ISSUE TITLE
Update a column value to null

### ISSUE THREAD

**Issue by sno6** [facebook/ent#1119]
Hello,

Is it possible to set a value to null using an update on an optional/nillable field.

**Comment by sno6** [comment]
I've found `ClearFieldX()` but it would be nice to have something such as `SetFieldX()` which takes a pointer value if the field is nillable, and sets to either null or the given value.

**Comment by a8m** [comment]
Hey @sno6 and thanks for suggesting this feature.

As you mentioned, we already have an option for this named `Clear<Field>`. However, if you want to extend the update-builder with your new option, go ahead and add it to your project using [custom templates](https://entgo.io/docs/templates/) - it's a super simple thing to do.

Closing, but please let me know if you need any help with this 😃

**Comment by a8m** [comment]
Created you some example to start working with it.

```go
{{ define "nullsetter" }}
	{{/* Add the base header for the generated file */}}
	{{ $pkg := base $.Config.Package }}
	{{ template "header" $ }}

	{{/* Loop over all updaters and implement the "SetOrClear" method for all optional fields */}}
	{{ range $n := $.Nodes }}
		{{ $updater := $n.UpdateName }}
		{{ range $f := $n.Fields }}
			{{ if $f.Optional }}
				{{ $set := print "Set" $f.StructField }}
				{{ $clear := print "Clear" $f.StructField }}
				func (u *{{ $updater }}) SetOrClear{{ $f.StructField }}(value *{{ $f.Type }}) *{{ $updater }} {
					if value == nil {
						return u.{{ $clear }}()
					}
					return u.{{ $set }}(value)
				}
			{{ end }}
		{{ end }}
	{{ end }}
{{ end }}
```

**Comment by sno6** [comment]
You're a legend, cheers @a8m

**Comment by sno6** [comment]
One small correction if anyone comes across this in the future.

Line 17 should be:

```
return u.{{ $set }}(*value)
```

instead of 

```
return u.{{ $set }}(value)
```

**Comment by a8m** [comment]
Thanks for the feedback @sno6, I'll update my comment.

**Comment by erlendp** [comment]
I don't understand why the behaviour of `SetNillableX` when passing a nil value would not be to update the database field to nil. Without this, the user is forced to conditionally call ClearFieldX or SetFieldX in the majority of cases. Neat that we can add custom behaviour with templates, but to me this should be be part of the contract of SetNillable. The current behaviour appears to be to silently do nothing if a nil value is passed in a a parameter.

**Comment by eouw0o83hf** [comment]
The library now contains another update path, which makes the script posted above a little stale. This updates it to be most useful as of this date.

```
{{ define "nilsetter" }}
	{{/* Add the base header for the generated file */}}
	{{ $pkg := base $.Config.Package }}
	{{ template "header" $ }}

	{{/* Loop over all updaters and implement the "SetOrClear" method for all optional fields */}}
	{{ range $n := $.Nodes }}
		{{ $updater := $n.UpdateName }}
		{{ range $f := $n.Fields }}
			{{ if $f.Optional }}
				{{ $set := print "Set" $f.StructField }}
				{{ $clear := print "Clear" $f.StructField }}
				func (u *{{ $updater }}) SetOrClear{{ $f.StructField }}(value *{{ $f.Type }}) *{{ $updater }} {
					if value == nil {
						return u.{{ $clear }}()
					}
					return u.{{ $set }}(*value)
				}

				func (u *{{ $updater }}One) SetOrClear{{ $f.StructField }}(value *{{ $f.Type }}) *{{ $updater }}One {
					if value == nil {
						return u.{{ $clear }}()
					}
					return u.{{ $set }}(*value)
				}
			{{ end }}
		{{ end }}
	{{ end }}
{{ end }}
```

**Comment by stonymahony** [comment]
@eouw0o83hf  Thanks for the great template!

I had to add a check to see if the field is not immutable, otherwise the updater has no set and clear.

`{{ if and ($f.Optional) (not $f.Immutable)}}`
