### ISSUE TITLE
How to `SELECT WHEN ... CASE ...` (and order on it)

### ISSUE THREAD

**Issue by rubensayshi** [facebook/ent#1161]
I hate to do one of these, but I can't seem to figure out how to do the query I want to do ...

a simplified version of the query I want to do:

```sql
SELECT * 
FROM `items`
WHERE `name` LIKE '?%' OR `name` LIKE '%?%'
ORDER BY (WHEN `name` LIKE '?%' THEN 2 WHEN `name` LIKE '%?%' 1 ELSE 0) DESC
```

which should find any record where the name begins with or contains my search param, and if it begins with the search param it should have priority over the ones which contain it. 

I've been trying to fiddle with doing `client.Item.Query().Where(...)` and using the `sql.Selector` to set the query, but the problem is that I can't set the `args` so I'd have to manually inject the search param into the `LIKE %?%` which would open me up for sql injections ...

**Comment by a8m** [comment]
Hey @rubensayshi, the framework doesn't support this at the moment, because it's not supported by all dialects.
But I'm working on changing the SQL builder right now, so I hope to post here a solution soon.

**Comment by rubensayshi** [comment]
ye I kinda figure that the only way to make that possible is if `Selector { order []string }` would be changed to something which implements `Querier` ...

Maybe that's actually a decent option? (and maybe same for `columns []string`?)

or add something like `ExtraArg(arg string)` to `Selector`, but that's pretty ugly ...

**Comment by a8m** [comment]
Hey @rubensayshi. I just merged https://github.com/facebook/ent/pull/1162.

This should make it possible for you to add "ORDER BY" clauses as follows:
```go
pets, err := client.Pet.
	Query().
	Order(ent.Asc("name")).
	Order(func(s *sql.Selector, check func(string) bool) {
		// The check function returns "false" if the given field
		// doesn't exist in the table.
		s.OrderExpr(sql.Expr("CASE ... END", args..))
	}).
	All(ctx)
```

Of course, you can make the API more friendly by adding custom code to your generated assets using external-templates. 

Closing, but feel free to continue the discussion or re-open if have you any problem with it.

**Comment by a8m** [comment]
This example should be added to our [FAQ](https://entgo.io/docs/faq/) page by the way.

**Comment by rubensayshi** [comment]
awesome!
