### ISSUE TITLE
Add additional import with custom template?

### ISSUE THREAD

**Issue by kuoruan** [facebook/ent#1197]
I already defined `import/additional` in my custom template like:

```
{{ define "import/additional" }}
    _ "github.com/facebook/ent"
{{ end }}
```

but the import not output to my go files.

Version: v0.5.4

**Comment by a8m** [comment]
Hey @kuoruan, can you provide some test repo to reproduce this? I just check this on master and it works for me. 

BTW, if you use the latest version, you can also name your templates as `"import/additional/<name>"` (this allow using multiple import templates), see: https://github.com/facebook/ent/blob/aa73b9067fb97275afc38f1f2750d2ba0e9edc7b/entc/gen/template/import.tmpl#L48-L52

**Comment by kuoruan** [comment]
Hi @a8m, here is a repo.

https://github.com/kuoruan/ent/tree/test_import

**Comment by a8m** [comment]
It looks like the codegen does include your additional imports. See [ent/config.go](https://github.com/kuoruan/ent/blob/test_import/ent/config.go#L9).

If you want these additional imports in your custom templates, add the "import" template in your custom template as follows:

```
{{ template "import" $ }}
```

**Comment by kuoruan** [comment]
It's working now, thanks. 😊
But all other generate files are contain my additional imports now, is there any way to prevent it?

**Comment by a8m** [comment]
> But all other generate files are contain my additional imports now, is there any way to prevent it?

Yes. If you're looking for adding the imports only for your custom template, don't use the "import" template (because it's used for all templates). For example, your template should look as follows:

```
{{ define "test_import" }}

{{ $pkg := base $.Config.Package }}
{{ template "header" $ }}

import (
    "<your package>"
    "<another package>"
    // ...
)

func TestImport() time.Time {
    return time.Now()
}
{{ end }}
```
