### ISSUE TITLE
Entity in Hook

### ISSUE THREAD

**Issue by masseelch** [facebook/ent#1201]
There is a little confusion going on here. I hope you can help. 

I have a hook like this:
```go
func DataChangedEntryHook() ent.Hook {
	return On(
		func(next ent.Mutator) ent.Mutator {
			return EntryFunc(func(ctx context.Context, m *ent.EntryMutation) (ent.Value, error) {
				// If the given entry is of type 'youtube' extract the data we need.
				if t, ok := m.GetType(); ok && t == schema.Youtube {
					if d, ok := m.Data(); ok {
                                                [...] // Do stuff with data
                                        }
				}

				// Proceed the chain.
				return next.Mutate(ctx, m)
			})
		},
		ent.OpUpdateOne|ent.OpCreate|ent.OpUpdate,
	)
}

// Hook is registered in main like this: c.Entry.Use(hook.DataChangedEntryHook())
```
I want to change a field of the entity when another field has a specific value. The above does only work, if the fields `type` and `data` get changed in the same mutation. If i just change `data` but leave `type`, `type` is not part of the mutation and therefore the above does not work. 

However there luckily is `OldType()`, at least so i thought. But `OldType` throws an error, if the Operation is not `ent.OpUpdateOne`, but i need this to work on entity creation too. 

So either hooks are the completely wrong place for this, or i still am missing something. What do i need to do to achieve what i described?

**Comment by a8m** [comment]
Hey @masseelch 😃 

First, if you want the hook to be executed only when specific fields were changes, you can use the [hook helpers](https://entgo.io/docs/hooks/#hook-helpers) as follows:

```go
func DataChangedEntryHook() ent.Hook {
	hk := func(next ent.Mutator) ent.Mutator { ... }
	return hook.If(
		hk,
		hook.And(
			hook.HasOp(ent.OpCreate|ent.OpUpdateOne|ent.OpUpdate),
			hook.HasFields(entry.FieldType, entry.FieldData),
		),
	)
}
```

But if I got your use-cases correctly, you try to get the value of the `type` field even if it wasn't changed in this mutation?
This won't work for update-many operations with `OldType`, because the field can be different between the entities.

**Comment by masseelch** [comment]
Nice, didnt know about the hook helpers. Kind of swopped over them in the docs. 

But yes indeed, i want the value of type even if it wasn't changed in that mutation. I have to move the logic to the handlers / service layer then. 

Thank you so much!
