### ISSUE TITLE
Adding field between two existing fields and generating throws interface {} is nil, not func() time.Time

### ISSUE THREAD

**Issue by arielitovsky** [facebook/ent#1208]
- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I have an existing schema definition that looks like this:
```

func (UserInvitation) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").
			MaxLen(34).
			NotEmpty().
			Unique().
			Immutable(),
		field.String("fieldA").NotEmpty().Immutable(),
		field.String("fieldB").Optional().Nillable(),
		field.Time("fieldC").Nillable().Optional(),
		field.Time("fieldD").Nillable().Optional(),
		field.Time("fieldE").Immutable().Default(time.Now),
		field.Time("fieldF").Default(time.Now).UpdateDefault(time.Now),
	}
}
```

If I try to add `fieldX` in the following manner:

```

func (UserInvitation) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").
			MaxLen(34).
			NotEmpty().
			Unique().
			Immutable(),
		field.String("fieldA").NotEmpty().Immutable(),
		field.String("fieldB").Optional().Nillable(),
                 field.String("fieldX").Optional().Nillable(),
		field.Time("fieldC").Nillable().Optional(),
		field.Time("fieldD").Nillable().Optional(),
		field.Time("fieldE").Immutable().Default(time.Now),
		field.Time("fieldF").Default(time.Now).UpdateDefault(time.Now),
	}
}
```

and then generate, I get the error: `interface conversion: interface {} is nil, not func() time.Time`. The error comes from:
runtime.go, which looks something like this:
model.DefaultFieldE = modelDescFIeldE.Default.(func() time.Time)

However, if I add this field at the end of the definition (after fieldF) everything works correctly.

## Expected Behavior 🤔

Adding a new field when there are existing .Time field should not throw errors.

## Steps to Reproduce 🕹

Steps:

1. Create the schema above
2. Run the schema
3. Add a new field (fieldX) in between existing fields.
4. Regenerate the code

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | go1.15.1 darwin/amd64  |
| Ent         | 0.5.4   |
| Database    | Postgres   |
| Driver      |         |

**Comment by a8m** [comment]
Hey @arielitovsky and thanks for reporting this.

Can you please update to latest master and report if you still face this issue? I just tried it locally and it works fine.

**Comment by arielitovsky** [comment]
Hi @a8m ,
Thanks for the quick response. I updated to the latest commit (v0.5.5-0.20210125064946-06ae79acbabf) and still have the exact same issue.

**Comment by arielitovsky** [comment]
To clarify, if I add fieldX as the last field in the definition, it works fine. It just fails when I add it after fieldB in the example above.

**Comment by arielitovsky** [comment]
I've figured out the problem. I had included a different definition of the runtime. Closing.
