### ISSUE TITLE
How to increment a number column

### ISSUE THREAD

**Issue by kyfk** [facebook/ent#1217]
How could I execute a query like the below?

```
UPDATE table SET column = column + 1;
```

I came up with the idea that I use the Query to get a record first and then update it.
But that idea required to be executing 2 queries at least.

**Comment by a8m** [comment]
Hey @kyfk, you can use the `Add<Field>` method on the `<T>Update`/`<T>UpdateOne` builder. For example:

```go
client.Debug().User.Update().AddAge(10).Exec(ctx)
// UPDATE `users` SET `age` = COALESCE(`age`, ?) + ? args=[0 10]

client.Debug().User.Update().AddAge(-5).Exec(ctx)
// UPDATE `users` SET `age` = COALESCE(`age`, ?) + ? args=[0 -5]

client.Debug().User.Update().AddAge(1).AddAge(2).ExecX(ctx)
// UPDATE `users` SET `age` = COALESCE(`age`, ?) + ? args=[0 3]
```

**Comment by kyfk** [comment]
That is great, thank you for your reply. @a8m
