### ISSUE TITLE
When the ID type is string, an exception occurs when using WithGlobalUniqueID

### ISSUE THREAD

**Issue by excing** [facebook/ent#1221]
Set the ID primary key type to string and use `WithGlobalUniqueID`, the following exception occurs:
```
panic: failed to create schema: sql/schema: error: the column "id" of the relationship "languages" is not an identity column (SQLSTATE 55000)
```

Database and version: **postgreSQL 13.1**

error code:

```
ctx = context.Background()
if err = client.Schema.Create(ctx, schema.WithGlobalUniqueID(true)); err != nil {
panic("failed to create schema: "+ err.Error())
}
```

Schema code:

```
// Language holds the schema definition for the Language entity.
type Language struct {
	ent.Schema
}

// Fields of the Language.
func (Language) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").
			MaxLen(3).
			NotEmpty().
			Unique().
			Immutable(),
		field.String("name"),
		field.Enum("direction").Values("ltr", "rtl").Default("ltr"),
	}
}

// Edges of the Language.
func (Language) Edges() []ent.Edge {
	return nil
}
```

In short, is it my code's wrong or ent does not support this type of setting?

Thanks

--------------------

PS: When using SQLite3 database, there is no problem.

**Comment by a8m** [comment]
Hey @excing 😃 

The [universal-id](https://entgo.io/docs/migrate/#universal-ids) option works only for numeric PKs as mentioned in the doc:

> How does it work? ent migration allocates a 1<<32 range for the IDs of each entity (table), and store this information in a table named ent_types. For example, type A will have the range of [1,4294967296) for its IDs, and type B will have the range of [4294967296,8589934592), etc.
> 
> Note that if this option is enabled, the maximum number of possible tables is 65535.


Can you elaborate on your use-case or what are you trying to do?

**Comment by excing** [comment]
Thank you, @a8m 

The case, I store the language code of iso639-2 as a table, and the article has a language field. 

Here, I want the article to be directly associated with the language code, so the code is used as the primary key of the language table.

**Comment by excing** [comment]
PS: When using SQLite3 database, there is no problem.

**Comment by a8m** [comment]
Got it.  Can I ask why do you use the universal-id option is your IDs aren't numerics?

**Comment by excing** [comment]
Sorry, I'm a novice. Can I use non-universal ID fields to associate other schemas?

**Comment by a8m** [comment]
Sure. Remove the `WithGlobalUniqueID` option for the schema-migration and it should work without any issues. 

Please let me know if you still have troubles with it, and feel free to open issues or comment if you need help 😃

**Comment by excing** [comment]
Ok. How do I do?

```golang
ctx = context.Background()
if err = client.Schema.Create(ctx); err != nil {
  panic("failed to create schema: "+ err.Error())
}
```

Like this? But I want the other schema enable the Universal-IDs, and this don't work.

**Comment by a8m** [comment]
`WithGlobalUniqueID` creates global ids for all tables in the database. This allows users to query any object by its ID without knowing its type on runtime (e.g. see the [GraphQL Node API](https://entgo.io/docs/graphql/#node-api)).  If your ID type is not consistent across all tables, you can't use this option. 

However, if you still want to use it, I'll suggest you to just replace the `"id"` field in your `Language` schema with other name (e.g. `"type"`), and use the default ID type for this schema. I hope it helps.

**Comment by excing** [comment]
Although this isn't what I want, it's also a way. Anyway, thank you very much for your reply.

**Comment by excing** [comment]
Although this isn't what I want, it's also a way. Anyway, thank you very much for your reply.

**Comment by wahello** [comment]
@a8m I confront the same problem with Postgres, while MySql has no the problem.

When use postgreSQL, error raised:
`
sql/schema: ERROR: column "id" of relation "groups" is not an identity column (SQLSTATE 55000)
`

**Comment by kevinxxq** [comment]
> @a8m I confront the same problem with Postgres, while MySql has no the problem.
> 
> When use postgreSQL, error raised:
> `sql/schema: ERROR: column "id" of relation "groups" is not an identity column (SQLSTATE 55000)`

Have you figured out this?

**Comment by TheBeachMaster** [comment]
This error still exists in Postgres, @a8m kindly reopen this issue.
