### ISSUE TITLE
v0.6.0 not working with entgql

### ISSUE THREAD

**Issue by dilipkk-foyernet** [facebook/ent#1228]
Looks like package path change to entgo.io is not updated to https://github.com/facebookincubator/ent-contrib and it is breaking generation when entgql is used

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

`go generate ./ent` is not working with entgql
## Expected Behavior 🤔

Expecting `go generate ./ent` works with entgql
## Steps to Reproduce 🕹

Steps:
1. Upgrade latest version 
1. Replace paths: `find . -type f -name '*.go'| xargs sed -i 's/github.com\/facebook\/ent/entgo.io\/ent/g'
1. Run `go generate ./ent`
1. Check errors: `./entc.go:25:3: cannot use entgql.AllTemplates (type []*"github.com/facebook/ent/entc/gen".Template) as type []*"entgo.io/ent/entc/gen".Template in field value`
## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.15.7  |
| Ent         | 0.6.0   |
| Database    | sqlite   |
| Driver      | https://github.com/mattn/go-sqlite3      |

**Comment by a8m** [comment]
Hey @dilipkk-foyernet, and thanks for reporting this. On it.

**Comment by a8m** [comment]
OK, https://github.com/facebookincubator/ent-contrib/pull/39 should fix the issue. I'll merge this soon.

**Comment by a8m** [comment]
Resolved. 

Closing, but please re-open if you still have troubles with it. Thanks 🙏
