### ISSUE TITLE
Why count query will transformed into count(distinct id)

### ISSUE THREAD

**Issue by fenngwd** [facebook/ent#1231]
Hi there,

I got a question about COUNT query. Why `CountNodes` will transformed into SQL `count(distinct id)`. Why's the design?

**Comment by alkanna** [comment]
It should only do that if your entity has been defined as Unique in its schema.
Have a look at `dialect/sql/sqlgraph/graph.go:598`
You should see this piece of code, that is driver agnostic :
```golang
if q.Unique {
		selector.SetDistinct(false)
		selector.Count(sql.Distinct(selector.C(q.Node.ID.Column)))
	}
```

**Comment by fenngwd** [comment]
thx.
