### ISSUE TITLE
Change to JSON tags not documented in 0.6

### ISSUE THREAD

**Issue by napei** [facebook/ent#1237]
Something in the ent template has broken JSON serialisation for the `EntityEdges` struct generated for each entity. Possibly from #318. Only present since `v0.6`

In my case, the edges struct has changed, adding json tags starting with lowercase, and subsequently has broken my frontend. Luckily I have a staging process and test environments 😅  

Technically, this is a breaking change.

![image](https://user-images.githubusercontent.com/8946502/106998530-c45da380-67d8-11eb-8e70-17c0d75335a3.png)

```go
// ProductEdges holds the relations/edges for other nodes in the graph.
type ProductEdges struct {
	// Translations holds the value of the translations edge.
	Translations []*ProductTranslation `json:"translations,omitempty"`
	// Merchant holds the value of the merchant edge.
	Merchant *Merchant `json:"merchant,omitempty"`
	// Categories holds the value of the categories edge.
	Categories []*Category `json:"categories,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}
```

Previously JSON output was using uppercase for edges:
```json
{
...
  "edges": {
    "Translations": {
    .....
    }
  }
}
```

and now it's 

```json
{
...
  "edges": {
    "translations": {
    .....
    }
  }
}
```

While this is technically how JSON is supposed to be represented, this wasn't documented at all in the release notes and finding this change was hard. Yes I probably should have reviewed the changes myself.

**Comment by a8m** [comment]
Oh! Sorry for this @napei. I missed this in my release note.

Adding this to the release note. Thanks for reporting this and hope it didn't cause too much troubles.

**Comment by napei** [comment]
All good. Perhaps an automated `CHANGELOG.md` script wouldn't be a bad idea? There's tons out there. I haven't used any specifically for go before but I'm sure it's not too hard.

**Comment by a8m** [comment]
> All good. Perhaps an automated `CHANGELOG.md` workflow wouldn't be a bad idea? There's tons out there. I haven't used any specifically for go before but I'm sure it's not too hard.

Yes, this can be a good idea. But I'll still need to go over it and make it more friendly for reading. 

Updated the release note. Thanks a lot for reporting this.
