### ISSUE TITLE
go get entgo.io/ent/cmd/ent: 404 Not found

### ISSUE THREAD

**Issue by pzeinlinger** [facebook/ent#1240]
- [ X] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

go get entgo.io/ent/cmd/ent fails with 
```
package entgo.io/ent/cmd/ent: unrecognized import path "entgo.io/ent/cmd/ent": reading https://entgo.io/ent/cmd/ent?go-get=1: 404 Not Found
```
The webpage returned:
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>ent/cmd/ent/index.html</Key>
<RequestId>3359626782C063A1</RequestId>
<HostId>
jOGdpVqS7TnPf/3hWp/Pt7Avl8n/K6n2iWY0c+oyIKbThi/PMjRtxPHB1uev2zpgkzXXyXqYZF0=
</HostId>
</Error>
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.15.6  |
| Ent         | 0.6.0   |

**Comment by a8m** [comment]
Hey hey @pzeinlinger and sorry for the troubles. I changed the import-path a few days ago, and figured out the [remote-path](https://golang.org/cmd/go/#hdr-Remote_import_paths) doesn't work as I thought for sub-packages. 

I fixed it, and it should work now without any issues (checked this locally). Closing
