### ISSUE TITLE
`go generate ./ent`  returns  `no schema found in: ./ent`

### ISSUE THREAD

**Issue by a-lucas** [facebook/ent#1250]
I am not sure if this is a bug, or just me not doing it the correct way.

All I did:

```bash
git add ent/schema 
git add ent/generate.go
```

With a `go.mod` at the root of my project.

Then:

on a fresh clone, 
I ran

```
GO111MODULE=on go mod download
GO111MODULE=on go generate ./ent
```

It downloads a couple of dependencies on the generate script, then ends with `no schema found in: ./ent`.

I am quite sure I missed a step.

**Comment by a8m** [comment]
Hey @a-lucas, my guess it's something in your local environment. 

Did you follow the steps in the [getting-started doc](https://entgo.io/docs/getting-started)? Can you paste the content of your `ent/generate.go` file? Do you have schemas in the `ent/schema` package? 

Please see the [getting started example](https://github.com/facebook/ent/tree/master/examples/start) in the examples directory.

**Comment by a-lucas** [comment]
Good day @a8m ,

Thanks, BTW, I really find `ent` awesome !

Yes a small set of schemas [schemas](https://gitlab.com/a-lucas/permalib/-/tree/dev/ent/schema) 

And the generate.go file is 

```go
package ent

//go:generate go run entgo.io/ent/cmd/ent generate ./schema
```

I just noticed that the `generate.go` version I have on the other machine is using `github.com/facebook/ent` repo, but I can't seem to find which `ent` version I used 2 weeks ago.

**Comment by a8m** [comment]
Thanks for the kind words @a-lucas 🙏 

> I just noticed that the generate.go version I have on the other machine is using github.com/facebook/ent repo, but I can't seem to find which ent version I used 2 weeks ago.

OK, does updating ent to latest master (or v0.6.0) solve your problem?

**Comment by a-lucas** [comment]
You're right @a8m, 

This has to do with a  version mismatch, the version I used to generate the project is 5.4.0, and I didn't originally committed the `generate.go` :sweat_smile: 

Legend!

No, v0.6.0 doesn't solve the issue, I'll downgrade ent to 0.5.4 first to see how it goes!

**Comment by a-lucas** [comment]
Replacing 
`//go:generate go run entgo.io/ent/cmd/ent generate ./schema`
by 
`//go:generate go run github.com/facebook/ent/cmd/ent generate ./schema`

Made it work.

**Comment by masseelch** [comment]
@a8m  Sorry to necropost

I have the same problem. However, i have the `schema` folder outside of the `ent` folder. Is this an anti-pattern?

**Comment by a8m** [comment]
> I have the same problem. However, i have the `schema` folder outside of the `ent` folder. Is this an anti-pattern?

Hey @masseelch, that's OK. I use it by myself in some places (see [an example in integration tests](https://github.com/ent/ent/blob/master/entc/integration/gremlin/ent/generate.go#L7)). 

Please let me know if you need any help with this.

**Comment by masseelch** [comment]
I'll try to create a reproducible example, where you get the error but the code works. If i succeed i create an issue for it. Thanks!
