### ISSUE TITLE
Adding a Custom Predicate

### ISSUE THREAD

**Issue by cliedeman** [facebook/ent#355]
Is it possible to add custom predicates?

The append method on predicate is private

```
func CustomPredicate(key string) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		p := &sql.Predicate{}
		... some custom sql...
		s.Where(p)
	})
}
```

**Comment by a8m** [comment]
Hey @cliedeman, 
You're welcome to add a PR and change this.

It's likely going to change soon with the custom types support (custom types need to support user-defined predicates).

**Comment by cliedeman** [comment]
This was implemented
