### ISSUE TITLE
Feature request: database schema in entity configs

### ISSUE THREAD

**Issue by alexeyco** [facebook/ent#663]
Quite often, it becomes necessary to place different tables in different database schemas, not only in `public`. It would be nice to get support for this case from `ent`.

It might look something like:
```go
func (User) Config() ent.Config {
    return ent.Config{
        Table:  "my_table",
        Schema: "my_schema",
    }
}
```

**Comment by a8m** [comment]
Hey @alexeyco and thanks for proposing this issue.

Named schema is a feature of PostgreSQL and I'm not sure we want to add it to the ent schema. However, 2 things about it:
1. I think you can achieve it today by using the "search_path" parameter in the connection string - I didn't check this, so if you tried it, let us know if it works for you.
2. We plan to re-structure the migration API soon and it'll provide a way to control the schema.

**Comment by alexeyco** [comment]
> 1. I think you can achieve it today by using the "search_path" parameter in the connection string - I didn't check this, so if you tried it, let us know if it works for you.

No, I can't – tables can be placed in different schemas. The dot in the table name breaks everything

**Comment by marwan-at-work** [comment]
Just FYI: 

I was able to get around the issue (for MySQL) by doing a couple of hacky things: 

1. Put the database name in the table itself
2. Add `r == '.'` to this function: https://github.com/facebook/ent/blob/e1fe2267bc56e57ceeaf1bf8dfb322d16c4b5f95/entc/gen/func.go#L112
3. Remove all backticks from queries. I did it by doing a ReplaceAll here which is obviously just a workaround as I am not familiar with how the query is constructed and how I can remove those backticks more properly: https://github.com/facebook/ent/blob/e1fe2267bc56e57ceeaf1bf8dfb322d16c4b5f95/dialect/sql/sqlgraph/graph.go#L550

**Comment by marwan-at-work** [comment]
@a8m any idea if this is something that ent will support? 🙏 

If so, would love to know what the API would look like as I'm not too familiar with ent's internals (yet!).

Thanks!

**Comment by a8m** [comment]
> @a8m any idea if this is something that ent will support? 🙏

Yes.

> If so, would love to know what the API would look like as I'm not too familiar with ent's internals (yet!).

I promise to give it more attention in the upcoming days.

**Comment by marwan-at-work** [comment]
@a8m that's great! Thanks for all of your work 🎉

**Comment by a8m** [comment]
Hey, some update regarding this issue.

The `Annotations` option will be added to the schema config, and we'll use it to pass the **schema** option to the SQL templates. 
The `Table` option in `ent.Config` will be moved to annotation as well. Here's an example how I think that API will look like:

```go
func (User) Config() ent.Config {
    return ent.Config{
        Annotations: []ent.Annotations{
                entsql.Annotation{Table: "...", Schema: "...", Charset: "...", ... },
                entgql.Annotation{/* other annotations */ },
        }
    }
}
```

The `entsql.Annotation` option will make it possible to address more issues we have today, and allow users to control the columns and FKs configuration.

**Comment by marwan-at-work** [comment]
@a8m that sounds great. Looking forward to it!

**Comment by marwan-at-work** [comment]
@a8m any luck here and/or anything I can do to help? 

Thanks!

**Comment by a8m** [comment]
Hey all, I want to add this feature really soon, and currently have an implementation working with static schema configuration using annotation as mentioned above (e.g. `entsql.Annotation{Schema: "public", ...}`). However, I don't think static config is good enough for such problem, and I'm re-thinking about it atm. Any thoughts or ideas are more than welcome! Thanks 😃

**Comment by marwan-at-work** [comment]
Hey @a8m , thanks for the update! I think static configuration is definitely a great start, and for my own purposes is probably more than enough. 

That said, here are the two places I can see dynamic schema configurations can happen (knowing that certain models/tables will have different schemas/db-names): 

- First: At client initialization level: aka `ent.Open("<driver>", "<conn>", options...)` -- I imagine the following option: 

```golang
ent.Open("mysql", conn, ent.WithSchema(
  user.Schema("users_db"),
  car.Schema("cars_db"),
))
```

Or perhaps, have it take the same exact Annotation type: 

```golang
ent.Open(
  "mysql",
  conn,
  user.WithAnnotations(entql.Annotation{Schema: "users_db"}),
  car.WithAnnotations(entql.Annotation{Schema: "cars_db"}),
)
```


- Second: At query/mutation level:


```golang
c, _ := ent.Open(...)
c.User.WithSchema("users_db").Query().Where(...).All(ctx)
```


That said, I'd be surprised if there was enough demand/usecase for when a program doesn't know the dbname of a table _until_ they're about to fire a query. 

So personally, I'd be in favor of Option 1 or honestly just the static one is also fine. 

Thanks again!

**Comment by marwan-at-work** [comment]
@a8m the more I think about it, I think Option 1 here is most idiomatic because DBNames are always _runtime_ initialized. If you take the [MySQL driver](https://github.com/go-sql-driver/mysql#usage) as an example, `dbname` is part of the connection URL. 

So option 1 would fit nicely because DBNames are determined at "constructor time" which is neither statically in the schema, nor at query time. 

Let me know what you think :v:

**Comment by a8m** [comment]
Issue resolved. Please see the [sql/schemaconfig](https://entgo.herokuapp.com/docs/feature-flags/#schema-config) feature-flag if you want to use it.

Thanks @alexeyco for the proposal and thanks @marwan-at-work for working on this  🙏
