### ISSUE TITLE
Question: How to make another column as id without renaming it in schema

### ISSUE THREAD

**Issue by fython** [facebook/ent#688]
After I run my demo in the first time, I noticed that `id` column has been defined in schema by default.

```
Error 1054: Unknown column 'my_table.id' in 'field list'
```

Then I read [ID Field](https://entgo.io/docs/schema-fields/#id-field) and try to set another column in my table as `id`:

```go
field.Int(`id`).StorageKey(`id_one`)
```

In this way, when I access `id_one` column by generated code, its field name isn't `obj.IdOne` but `obj.Id`.

Is there any way to make another column as id without renaming it in schema?

**Comment by a8m** [comment]
Hey @fython!

> Is there any way to make another column as id without renaming it in schema?

I'm not sure I get the question. If you define the ID field explicitly, you override the default ID definition, and the `StorageKey` is used to configure a different name for the column name in SQL.

**Comment by sillygeniuss** [comment]
> Hey @fython!
> 
> > Is there any way to make another column as id without renaming it in schema?
> 
> I'm not sure I get the question. If you define the ID field explicitly, you override the default ID definition, and the `StorageKey` is used to configure a different name for the column name in SQL.

Hey, @a8m , i also found this problem.How can i set a custom name for field ID. I have try the function `StorageKey` and `StructTag` in my code, but field ID is not shown as the custom name i set in the table file generated by entc.

**Comment by a8m** [comment]
Hey @sillygeniuss!
What do you mean by custom name? The name of the struct field in Go, or the name of the column in the database?

**Comment by a8m** [comment]
> The name of column in database.

Use the `StorageKey` option. There are a few examples in this project. [Here's one of them](https://github.com/facebook/ent/blob/fd0a7f9/entc/integration/customid/ent/schema/user.go#L19-L24) 😃

**Comment by sillygeniuss** [comment]
![image](https://user-images.githubusercontent.com/59204202/91028807-9290c000-e630-11ea-98a6-42b4d8272812.png)
Like the picture above. The code is generated by using `StorageKey("biz_id")`.May i consider the field ID will use "biz_id" in sql when i insert a row?

**Comment by a8m** [comment]
> Like the picture above. The code is generated by using StorageKey("biz_id").May i consider the field ID will use "biz_id" in sql when i insert a row?

Yes. Check the `ent/migrate/schema.go` generated table information.

**Comment by sillygeniuss** [comment]
![image](https://user-images.githubusercontent.com/59204202/91030794-4b0b3380-e632-11ea-8b82-269da9bbd135.png)
It seems not as u say. The name remains "id", i want change the name to "biz_id".

**Comment by a8m** [comment]
Can you post here your schema configuration please?

**Comment by sillygeniuss** [comment]
> Can you post here your schema configuration please?

Oh, my fault. I use the function `StructTag ` to generate code. Sorry for wasting ur time.

**Comment by a8m** [comment]
No problem 😃
Closing, but feel free to continue the discussion if you still have questions.

**Comment by sillygeniuss** [comment]
> No problem 😃
> Closing, but feel free to continue the discussion if you still have questions.

Thx, bro.
