### ISSUE TITLE
Question: Is there a support for Postgres's Declarative Partitioning

### ISSUE THREAD

**Issue by unique1o1** [facebook/ent#689]
Hey, I was wondering if `ent` supports Postgres's Declarative Partitioning? 
If not is there a work-around? Like modifying the migration files.

**Comment by a8m** [comment]
Hey @unique1o1 and thanks for raising up this issue.

> If not is there a work-around?  Like modifying the migration files.

Not at the moment, but in the near future, we're going to post the proposal for the new migration API (it will be possible to customize the migration files with the new API).

**Comment by a8m** [comment]
Closing, but feel free to continue the discussion if you still have comments/questions.

Thanks 😃

**Comment by xin-hao-awx** [comment]
Just wondering that is this issue have been finished or dropped?
