### ISSUE TITLE
Eager loading not working when using Select

### ISSUE THREAD

**Issue by aca** [facebook/ent#694]
Hi, glad to hear that it is now the facebook project! (I'm not sure what that means though.. 😅) Really appreciate your hard work.

I'm having trouble with eager loading feature. Here's how the table looks like.
```
// Fields of the User.
func (User) Fields() []ent.Field {
        return []ent.Field{
                field.String("name"),
                field.String("huge_text"),
        }
}

// Edges of the User.
func (User) Edges() []ent.Edge {
        return []ent.Edge{
                edge.From("teams", Team.Type).Ref("users").Unique(),
        }
}
```

```
// Fields of the Team.
func (Team) Fields() []ent.Field {
        return []ent.Field{
                field.String("name"),
        }
}

// Edges of the Team.
func (Team) Edges() []ent.Edge {
        return []ent.Edge{
                edge.To("users", User.Type),
        }
}
```
The query I wanted to achieve is this, `db.Debug().User.Query().Where(user.NameEQ("smith")).WithTeams().AllX(ctx)`. But without huge_text column.

 ```
db.Debug().User.Query().Where(user.NameEQ("smith")).WithTeams().Select(user.FieldName).Scan(ctx, &u)
2020/08/26 05:02:41 driver.Query: query=SELECT `users`.`name` FROM `users` WHERE `users`.`name` = ? args=[smith] 
```
But It seems that it eager loading feature is not working when Select / Scan is used.
It doesn't generate required query ```driver.Query: query=SELECT DISTINCT `teams`.`id`, `teams`.`name` FROM `teams` WHERE `teams`.`id` IN (?) args=[1] ``` 
And returns with no error.

**Comment by a8m** [comment]
Hey @aca!

> But It seems that it eager loading feature is not working when Select / Scan is used.

Eager loading doesn't work with `Scan` in purpose. In the future, we'll add support for using `Select` with the `All`/`Only`/etc (together with the GraphQL integration). But that's an expected behavior.

**Comment by aca** [comment]
```we'll add support for using Select with the All/Only/etc``` That's nice. I also think that is proper way.
