### ISSUE TITLE
Question: Unique constraint on combination of two columns?

### ISSUE THREAD

**Issue by unique1o1** [facebook/ent#695]
While searching the docs I only found a unique constraint for a single column.

**Comment by a8m** [comment]
Hey @unique1o1! Please use the [schema.Indexes](https://entgo.io/docs/schema-indexes/) configuration for setting it.

**Comment by unique1o1** [comment]
also what about primary key combinations?

**Comment by a8m** [comment]
> also what about primary key combinations?

What's not working with [schema.Indexes](https://entgo.io/docs/schema-indexes/)?

**Comment by unique1o1** [comment]
Is it possible to add a composite primary key? 
I need to make the id column and time column a composite primary key for timescaleDB for a hypertable.

**Comment by a8m** [comment]
The composite PK option is not supported at the moment in ent - see https://github.com/facebook/ent/issues/400

**Comment by a8m** [comment]
If you'll subscribe #400, you will be notified when we address it. Thanks 😃

**Comment by unique1o1** [comment]
Ok, thanks
