### ISSUE TITLE
Question: Default struct tags for edges?

### ISSUE THREAD

**Issue by asonawalla** [facebook/ent#704]
I've noticed that ent chooses to specify default JSON struct tags for fields, but not for edges, as is apparent in the [base case example](https://github.com/facebook/ent/blob/master/examples/start/ent/user.go#L17-L40).  It's clearly trivial to override this behavior using the `StructTag` method in a schema definition, but I wanted to ask if there is a reason for the discrepancy in defaults.

PS - thanks for publishing this library; it looks like it's going to save my team a lot of time!

**Comment by a8m** [comment]
Hey @asonawalla! There's no specific reason behind it, but if we'll decide to add this at some point, we'll need to check before that it doesn't break any existing behavior in our side. 

Like you mentioned, you can use the `StructTag` option to configure it for your needs atm 😃 


> PS - thanks for publishing this library; it looks like it's going to save my team a lot of time!

I'm glad you like it!

**Comment by asonawalla** [comment]
Sounds good - thanks!
