### ISSUE TITLE
Question: Edge to another package

### ISSUE THREAD

**Issue by vahid-sohrabloo** [facebook/ent#707]
Is there any way to edge to another package?

**Comment by a8m** [comment]
Hey @vahid-sohrabloo!
I’m not really sure what does it mean. Can you please elaborate on the use case?

**Comment by vahid-sohrabloo** [comment]
```
mypakcage
├── barpackage
│   └── ent
│       └── schema
│           └── bar.go
└── foopackage
    └── ent
        └── schema
            └── foo.go
```
I want to M2M between Bar Entity (bar.go) and Foo Entity (foo.go)

**Comment by a8m** [comment]
This option is not supported (and we don't have plans to support it). Thanks!

**Comment by a8m** [comment]
Closing, but of course, feel free to continue the discussion if you want 😃
