### ISSUE TITLE
Custom Primary Key field?

### ISSUE THREAD

**Issue by davedray** [facebook/ent#709]
> ID Field
> The id field is builtin in the schema and does not need declaration. In SQL-based databases, its type defaults to int (but can be changed with a codegen option) and auto-incremented in the database.

> In order to configure the id field to be unique across all tables, use the WithGlobalUniqueID option when running schema migration.

> If a different configuration for the id field is needed, or the id value should be provided on entity creation by the application (e.g. UUID), override the builtin id configuration.

It seems that the type of the ID field is configurable, but not the name of it?  We're thinking of adopting ent in an existing project, but the database named each primary key `uuid` instead of `id` and there doesn't seem to be a way to configure that.

**Comment by a8m** [comment]
Hey @davedray! Use the `StorageKey` option to configure the column name in the database (the Go field will still be named as `ID`). See [example](https://github.com/facebook/ent/blob/fd0a7f9/entc/integration/customid/ent/schema/user.go#L21-L22) in integration tests (or search in the [docs](entgo.io)).
