### ISSUE TITLE
Run `entc describe  ./ent/schema`  got error

### ISSUE THREAD

**Issue by fezho** [facebook/ent#719]
I use the demo schema in `getting-started`,  and want to run `entc describe`, but it returns the following error:
```
entc/load: # command-line-arguments
.entc/entc_github.com_xxx_ent-demo_ent_schema_1598859594.go:124:3: cannot use fd.Enums (type []struct { N string; V string }) as type map[string]string in field value
```

My ent version is v0.4.2

**Comment by a8m** [comment]
Hey @fezho!
Looks like your ent and entc versions are incompatible (see [docs](https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent)). 

Update your entc, or use: 
```
go run github.com/facebook/ent/cmd/entc describe <schema>
```
