### ISSUE TITLE
Question:  How to delete two object bind

### ISSUE THREAD

**Issue by kasuganosora** [facebook/ent#722]
We are have three tables:

posts:
|id | title|

tags:
id |title

post_tag:
id| post_id | tage_id
name | age

How to use ent delete post_tag record? thx

**Comment by a8m** [comment]
Hey @kasuganosora!

If these 2 objects are managed by ent, you can do it as follows:

```go
post, err := post.Update().
    RemovedTags(tags...).
    Save(ctx)
```

**Comment by kasuganosora** [comment]
think a8m
