### ISSUE TITLE
 How to Query All Entityies randomly

### ISSUE THREAD

**Issue by kosgug** [facebook/ent#726]
I want to Query All Entityies randomly, but there was no way found

**Comment by a8m** [comment]
Hey @kosgug, can you be more specific what do you mean by "randomly"? Something like, `ORDER BY RAND()`?

**Comment by kosgug** [comment]
@a8m

Yeah,  for example codes:

`util.DBC.Posts.
		Query().
		Order(ent.Asc("?? RAND() ??")).
		All(util.Ctx)`

**Comment by a8m** [comment]
You can do it as follows:
```go
posts, err = client.Post.
	Query().
	Order(func(s *sql.Selector) {
		s.OrderBy("RAND()")
	}).
	All(ctx)
```
Or, you can add it to your generated code using [external-template](https://entgo.io/docs/templates).

**Comment by kosgug** [comment]
@a8m  Cool, thanks for your help.

And i have a problem using this code in my project, i detailed entgo is a great project, so, if there's a better way, please share with me.

### Env
- Database: pgsql
- Entgo Version: v0.4.2

### My Codes
```
questions, err = client.Question.
	Query().
	Order(func(s *sql.Selector) {
		s.OrderBy("random()")
	}).
	All(ctx)
```

### Bugs
`PG::Error: SELECT DISTINCT, ORDER BY expressions must appear in select list`

### Fix Method
1. Find func querySpec() on `ent/question_query.go` file
2. Change default code `Unique: true,`  to `Unique: false,`
3. Done
