### ISSUE TITLE
GetX in client.tmpl has naming collision when the struct name abbreviates to id

### ISSUE THREAD

**Issue by kevpie** [facebook/ent#733]
In my case `ImageData` is being abbreviated to `id` which colides

```sh
# entc init ImageData
# entc generate ./ent/schema
```

**client.tmpl**
```go
// GetX is like Get, but panics if an error occurs.
func (c *{{ $client }}) GetX(ctx context.Context, id {{ $n.ID.Type }}) *{{ $n.Name }} {
	{{ $rec }}, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return {{ $rec }}
}
```

**client.go**
```go
// GetX is like Get, but panics if an error occurs.
func (c *ImageDataClient) GetX(ctx context.Context, id int) *ImageData {
	id, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return id
}

```

**assignment type collision**
![Screen Shot 2020-09-06 at 2 33 42 PM](https://user-images.githubusercontent.com/163482/92335685-13e34c00-f04e-11ea-89e8-d5556c7adffd.png)

**return type collision**
![Screen Shot 2020-09-06 at 2 27 16 PM](https://user-images.githubusercontent.com/163482/92335604-201ad980-f04d-11ea-98a0-b890fffc3ebd.png)

**Comment by a8m** [comment]
Thanks for reporting this issue @kevpie!  

We can fix it by just changing `{{ $rec }}` to a static variable name (e.g. `obj`). Do you want to send a patch?

**Comment by kevpie** [comment]
Hi @a8m I think I can send a patch. It may be a few days before I do as I'm exploring use of `ent` at the moment in a current project.

**Comment by kevpie** [comment]
Hi @a8m,
PR #750 submitted as per your suggested fix.

**Comment by a8m** [comment]
Wonderful! Thanks @kevpie for reporting this issue and for the fix.
