### ISSUE TITLE
go test is failing: no such function: JSON_EXTRACT

### ISSUE THREAD

**Issue by dilipkk-foyernet** [facebook/ent#734]
Operating system: Ubuntu 20.04
Go version: 1.15.1
Directory: `entc/integration`
command:  `go test ./...`

This command is giving following error:
```
json_test.go:187: 
                Error Trace:    json_test.go:187
                                                        json_test.go:97
                Error:          Received unexpected error:
                                no such function: JSON_EXTRACT
                Test:           TestSQLite
FAIL
```
How to fix this error?

**Comment by a8m** [comment]
Hey @dilipkk-foyernet! You need to build sqlite with `json1` tag - see [go-sqlite](https://github.com/mattn/go-sqlite3#features) doc. 

BTW, JSON predicates are not yet official in entgo.io docs, so if you use the API under `dialect/sql`, you should expect a breaking change soon :| (it'll be mentioned in the release note).
