### ISSUE TITLE
question about updater

### ISSUE THREAD

**Issue by Jack-Ji** [facebook/ent#737]
Hi, just wondering is it OK to chain RemoveXXX && AddXXX together ? e.g.

```
    client.SomeTable.
        UpdateOneID(id).
        RemoveSomeEdges(...).
        AddSomeEdges(...)
        Save(ctx)
```

**Comment by a8m** [comment]
Hey @Jack-Ji! Yes, just created a PR (https://github.com/facebook/ent/pull/738) to show that it's possible.
Closing.

**Comment by Jack-Ji** [comment]
Nice, thanks for quick update!
