### ISSUE TITLE
Hooks can't be used to set a required edge

### ISSUE THREAD

**Issue by stffabi** [facebook/ent#739]
If an entity has a required edge defined and one tries to set it with a `OpCreate` hook depending on context values, the save doesn't work.

[PreSave here](https://github.com/facebook/ent/blob/ebfc1a4f36db57dec40dba9c0cf2325b974c2ea0/entc/gen/template/builder/create.tmpl#L37) will be called before calling the hooks [here](https://github.com/facebook/ent/blob/ebfc1a4f36db57dec40dba9c0cf2325b974c2ea0/entc/gen/template/builder/create.tmpl#L60).

Would it be possible to allow hooks setting required edges?

**Comment by a8m** [comment]
Hey @stffabi and thanks for reporting this issue.
It does make sense to run the validators after the hooks were called - we just need to make sure it doesn't break existing behavior.

**Comment by stffabi** [comment]
That would be awesome. It would also be more robust, because it could also happen that hooks might clear a required edge. Which should also be detected by the validators.

**Comment by stffabi** [comment]
Awesome, thanks for the fast fix.
