### ISSUE TITLE
Question: Expressing one-to-many relationship with multiple types

### ISSUE THREAD

**Issue by fwielstra** [facebook/ent#743]
I've done some research and this is actually a difficult one in database design, as it turns out.

I have a `Config` type, a plain type with fields like ID, description, last modified, etc.

A `Config` has 0-n "steps" or "module configurations"; each step has an "order" property with relation to the Config (plain number).

Each Step can be of a different type though; there's about a dozen different "modules" that can be configured.

I have some ideas on how to express this in vanilla SQL; one option is a link table with a 'type' column, but I'm not sure how to query it in one go; probably would need multiple queries (n+1 problem). Mind you, the application I'm building is not that big / will not have that many users (the biggest user has about 100 `Config` types, I believe they would have <100 `steps`, and in the range of <100 users total, probably a lot less concurrent users).

Sketched out:

## table `config`

| Field | Type |
| ----- | ---- |
|id|int|
|name|string|

##  table `config_module`

|name|type|
|----|----| 
|config_id|int|
|module_id|int|
|order|int|
|type|string|

##  table `module_foo`

|name|type|
|----|----|
| id | int |
| foo | string |
| bar | bool |

## table `module_bar`

|name|type|
|----|----|
| id | int |
| baz | int |
| qux | string |

## Example data in table `config_module`

| config_id | module_id | order | type |
| --------- | ---------- | ----- | ---- |
| 1 | 1 | 1 | 'foo' |
| 1 | 2 | 2 | 'foo' |
| 1 | 3 | 3 | 'bar' |
|2 | 1 | 4 | 'bar' |
| 2 | 2 | 5 | 'bar' |

The other option I can think of would be a 'wide' link table, where only one of the `module` columns will have a value:

|name|type|
|----|----|
| config_id | int |
| order | int |
| module_foo_id | int |
| module_bar_id | int |

My main questions: Is there a solution to this use case? Is this something supported by Ent by default, or would I need some custom SQL? Am I on the right track or should I consider an alternative table structure? (e.g. turn it into a key / value store where each module property is in a single table, where the property name is encoded in a row)

(minor edit: accidentally hit cmd+enter, submitting the issue prematurely)

**Comment by a8m** [comment]
Hey @fwielstra,
I hope I got your question right, but if I got it right - you can't have 1 edge-type that points to 2 different types (bar != foo, since they have different fields).

If I needed to do something like this, I would probably use something as follows:

```go
type ConfigModule struct {
	ent.Schema
}

func (ConfigModule) Fields() []ent.Field {
	return []ent.Field{
		field.Int("order"),
		field.Enum("type").
			Values("bar", "foo"),
	}
}

func (ConfigModule) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("config", Config.Type).
			Unique(),
		edge.To("foo_modules", ModuleFoo.Type),
		edge.To("bar_modules", ModuleBar.Type),
	}
}
```

Other option, is to create a table named "modules" and store a JSON object in each row (because content is different from type to type). I hope it helped.

**Comment by fwielstra** [comment]
Yeah I think what you're proposing would result in the "wide" link table that I mentioned. I've been working on the business logic and API end of this issue today and ended up with a similar approach; a struct with shared fields + module-specific, optional structs:

```go
type Config struct {
	ID       int
	Comments string
	// ...
	ModuleConfigs []*ModuleConfig
}

type ModuleName string

type ModuleConfig struct {
	Name      ModuleName
	Order     int
	FooConfig *FooConfig
	BarConfig *BarConfig
	BazConfig *BazConfig
}

type FooConfig struct {
	Foo string
	Bar int
	Baz bool
}

// etc
```

And this can be mapped to ent and persisted into a databas via non-required edges.

Alright, I think I can work with this. Thanks for the suggestions and validation! <3

**Comment by dilipkk-foyernet** [comment]
@a8m We also have this use case. Is it possible to add support for pseudo edges that might solve this issue?

```go
type ConfigModule struct {
	ent.Schema
}

func (ConfigModule) Fields() []ent.Field {
	return []ent.Field{
		field.Int("order"),
		field.Enum("type").
			Values("bar", "foo"),
	}
}

func (ConfigModule) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("config", Config.Type).
			Unique(),
		edge.To("foo_modules", ModuleFoo.Type),
		edge.To("bar_modules", ModuleBar.Type), 
                edge.Pseudo("modules", ["foo_modules", "bar_modules"])
	}
}
```
Pseudo edges are not persisted in the DB but provide functionality for the application to deal with edges of the same type, this can help to solve graphql interfaces in entgql.
Any thoughts on this?

**Comment by Erog38** [comment]
I love this concept, I was just looking around trying to see if I could represent an edge in this way. I'm building a tree where nodes may be of various types to facilitate the case of having edges to various types (as you may see in something like gremlin) I'm very curious to know if there have been other issues or requests around this ideology.
