### ISSUE TITLE
Bug: Add validation in schema Fields in case of name conflicts with mutation 

### ISSUE THREAD

**Issue by waro163** [facebook/ent#747]
My Fields is as follows:

```
func (Phone) Fields() []ent.Field {
	return []ent.Field{
		field.Int("user_id").Positive(),
		field.String("op"),
		field.String("number").MaxLen(11),
	}
}
```

(I have changed Phone Fields some times, e.g. add user_id field) 

after i run "go generete ./ent ", there is a file named "mutation.go", I get the code as follows:

```
type PhoneMutation struct {
	config
	op            Op
	typ           string
	id            *int
	user_id       *int
	adduser_id    *int
	op            *string
	number        *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Phone, error)
}
```

you can see it, in the PhoneMutation, i have two fields named "op",  when i run my app, the error "**ent/mutation.go:37:2: duplicate field op**" will be raised, 

so i think if someone add field named like "typ","done"... The same error will occur。

**Comment by a8m** [comment]
Thanks for reporting this issue @waro163! Issue resolved with #749.
