### ISSUE TITLE
How to Implement History Tracking

### ISSUE THREAD

**Issue by henrywoody** [facebook/ent#752]
I'm quite new to using ent, but I love the idea and have found working with it fairly easy so far.

I'm wondering what the best approach to implementing a history tracking system for records in ent is.

Another project I've been working on uses [Django Simple History](https://django-simple-history.readthedocs.io/en/latest/), which basically creates a history table for each table. Whenever a mutation (create, update, delete) is performed, a row is inserted into the corresponding history table with the new (or last in the case of delete) version of the row along with a timestamp and user ID.

Is something like this possible using ent? If so what would be the best approach?

**Comment by a8m** [comment]
Hey @henrywoody! 
We actually do something similar internally, and we use [ent.Hooks](https://entgo.io/docs/hooks/#hooks) for implementing it.

You also want to give a look on the [external-templates](https://entgo.io/docs/templates/) option. It can help you generating many parts. 

Let me know if you need help with it.

**Comment by henrywoody** [comment]
@a8m thanks for the reply! Good to know that this can be done and I will definitely look more into hooks and external templates.

**Comment by a8m** [comment]
Sure.

Closing, but feel free to continue the discussion if you need further help with it.
