### ISSUE TITLE
Create entity from a struct

### ISSUE THREAD

**Issue by napei** [facebook/ent#761]
I looked around but couldn't find an easy way of creating an entity from an initialized struct. Currently I don't think this is possible as `Create()` can't take any arguments.

It would be great to be able to create an entity like this

```go
user := &ent.User{
    Age: 30,
    Name: "Nathaniel",
  },
}
user, err = client.User.Create(user).Save(ctx)
```

More specifically is there a good way to take JSON/struct, and convert it into a Database model. This is probably one of the biggest use-cases for this in use with APIs and such, where I don't really want to call `SetName()` and other functions for what is possibly many fields. 

Thanks 😄

**Comment by a8m** [comment]
Hey @napei and thanks for proposing this.

We actually have discussed this in the past in other issues, and we don't have plans to add support for this - see https://github.com/facebook/ent/issues/83#issuecomment-541557691.

If we'll accept struct in the builders, we won't be able to distinguish between zero/real values (e.g. `&ent.User{Age: 0, Name: ""}`), and may set incorrect values in the database, and also update unnecessary columns - we don't have plans to change the struct fields to pointers.

However, if users still want to add and use such functionality, they can use [external-templates](https://entgo.io/docs/templates/) and define their business logic in the new generated method - this is a pretty simple thing to do and it can also help accepting other structs in the builders, like GraphQL or Swagger inputs. If you need help with that, let me know. 

Closing, but feel free to continue the discussion if you want.

**Comment by napei** [comment]
Hey @a8m thanks for the quick response. I had a look at the template docs but a lot of it didn't make sense. I completely understand the reasoning behind not supporting this.

Are you able to, perhaps, provide an example or some direction on using templates? Further to that are there examples/packages out there that use ent in conjunction with a REST api for CRUD operations?

Perhaps instead of structs, the ability to create records from JSON could be a thing? Not providing values would mean those fields would be ignored, and providing a value would be an explicit call to the relevant `Set` function. Doing that without heavy use of `reflection` would probably be tricky.

**Comment by a8m** [comment]
> Are you able to, perhaps, provide an example or some direction on using templates? Further to that are there examples/packages out there that use ent in conjunction with a REST api for CRUD operations?

Did you see the example in the [website](https://entgo.io/docs/templates/#examples)? In the upcoming days, we're going to OSS our GraphQL integration. There are multiple examples there. I'll update the issue once it's out. 

> Doing that without heavy use of reflection would probably be tricky.

If you'll use custom templates, you won't need any reflection for this.

This is the general idea of such template - get an input, and call the setter of each field (still need to figure out how you distinguish between zero to real values). 

```
{{ range $n := $.Nodes }}
	{{ $builder := $n.CreateName }}
	{{ $receiver := receiver $builder }}
	
	func ({{ $receiver }} *{{ $builder }}) Set{{ $n.Name }}(input *{{ $n.Name }}) *{{ $builder }} {
		{{- range $f := $n.Fields }}
			{{- $setter := print "Set" $f.StructField }}
			{{ $receiver }}.{{ $setter }}(input.{{ $f.StructField }})
		{{- end }}
		return {{ $receiver }}
	}
{{ end }}
```
