### ISSUE TITLE
Question: Diagrams from docs

### ISSUE THREAD

**Issue by napei** [facebook/ent#765]
Those graph diagrams in the docs. Where do they come from?

Is it possible to generate them from ent?

**Comment by a8m** [comment]
Hey @napei,
This what I answered in #364 a few months ago:

> Hey caik13, we don't have something official and this photo was created manually by me.
> However, we started to work on some schema visualization using d3, that wasn't shipped (my fault), and I hope we can OSS it somewhere in the future (don't want to promise).
> 
> If you want to implement something and need guidance, don't hesitate to reach out.

The new update is that a new repository is ready (ent-contrib), and should be OSS in the upcoming days. This CLI tool may be OSS as well there (depends on @dlvhdr 😉).

**Comment by napei** [comment]
Wonderful news! Thanks 😄

**Comment by AlexanderMatveev** [comment]
I would like to add an idea: just generate some markdown acceptable by libraries like [mermaid](https://mermaid-js.github.io/mermaid/#/). I widely used mermaid in other orms and programming languages, so find it very useful.

**Comment by a8m** [comment]
That's nice! Never heard about mermaid, but it looks like a simple solution to generate such diagrams.

**Comment by rotemtam** [comment]
@AlexanderMatveev , that's really cool!

**Comment by a8m** [comment]
Thanks again @AlexanderMatveev for the reference. I created a CLI tool for generating ER diagrams for Ent schemas using mermaid. 

See https://github.com/a8m/enter

**Comment by rotemtam** [comment]
Nice @a8m !!

**Comment by AlexanderMatveev** [comment]
@a8m you're welcome, I'm glad you like it
