### ISSUE TITLE
Question: Documentation regarding integration with gqlgen

### ISSUE THREAD

**Issue by francismarcus** [facebook/ent#770]
Hello 👋
Regarding the documentation for the integration with gqlgen as mentioned by @a8m in r/golang 
Hows it coming along, have you gotten started with it? I think it it would be highly appreciated, if not by others then at least by me!

If you havn't gotten started with it, perhaps I could start and you can fill in with what I've gotten wrong / are unaware of.

Cheers

**Comment by a8m** [comment]
Hey @francismarcus and thanks for raising up this issue 😄 

The `ent-contrib` repository is  going to be OSS in the upcoming days, and it contains the initial integration with gqlgen (Node API, pagination, ordering, fields collection using auto eager-loading, and ent.Tx middleware for mutations).
Once it's out, you're welcome to join and help writing the documentation to it. I already started, but there are more work to do there.

**Comment by francismarcus** [comment]
@a8m sounds awesome, thanks for your work 🥇

**Comment by a8m** [comment]
Closed with https://entgo.io/docs/graphql. Please note that docs are WIP at the moment, and will be updated more along with examples in the future. Contributions are welcomed of course.
