### ISSUE TITLE
bug: wrong package used in runtime.go

### ISSUE THREAD

**Issue by napei** [facebook/ent#773]
I am using a mixin which provides a UUID (github.com/google/uuid) as the primary key with default values set which is working fine. But when I add a hook to a model the generated `ent/runtime/runtime.go` file is using the wrong import for uuid (github.com/gofrs/uuid)

This causes errors in `runtime.go` with the `testmodel.DefaultID = testmodelDescID.Default.(func() uuid.UUID)` line

I have created a reproduction here: https://github.com/napei/ent-uuid-test

There is  a second branch there called `no-mixin` which shows the issue with no mixin present but still using hooks.

**Comment by a8m** [comment]
Thanks for reporting this @napei. #775 should solved the problem. Please re-open if you have further issues.

**Comment by napei** [comment]
Thanks @a8m it's fixed using master with `go get -u` , but, using the latest has now caused a bunch of errors in all the `_query.go` files.

![image](https://user-images.githubusercontent.com/8946502/93450626-850de380-f919-11ea-9cb2-9220af326e61.png)

**Comment by a8m** [comment]
Your ent version and entc version are incompatible. Please follow this guide - https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent

**Comment by napei** [comment]
> Your ent version and entc version are incompatible. Please follow this guide - https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent

Thanks. I had to force an update with `go get github.com/facebook/ent/cmd/entc@38e769465c0181f79f52dbd11a70b33af49a3581` and all works now

**Comment by a8m** [comment]
Please use `go generate` (using `go run github.com/facebook/ent/cmd/entc`) instead of running `entc` directly.
