### ISSUE TITLE
Proposal Generate other file extension.

### ISSUE THREAD

**Issue by najBaby** [facebook/ent#780]
If we can generate other file extension like """shema.graphql""" for graphql or """todo.proto""" for grpc.
It will be awesome. I see your """entgql""" package. It is very attractive but we code too to implement.

**Comment by a8m** [comment]
Hey @najBaby!
We actually discuss about adding support for generating GraphQL types from ent types (along with user-defined mutations) to a new or an existing GraphQL schema - I'll probably create a proposal for it in the issue tracker before starting to work on it.

However, you don't need to be blocked on us. You can do it actually today - use the `entc` package for loading the schema to your Go program and then execute your custom template as follows:

```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/facebook/ent/entc"
	"github.com/facebook/ent/entc/gen"
)

func main() {
	path := "./ent/schema"
	if len(os.Args) > 1 {
		path = os.Args[1]
	}
	graph, err := entc.LoadGraph(path, &gen.Config{})
	if err != nil {
		log.Fatalln(err)
	}
	// Custom codegen goes here:
	if err := tmpl.Execute(schemaFile, graph); err != nil {
		log.Fatalln(err)
	}
}
```

Closing, but please let me know if you need any help with it.
