### ISSUE TITLE
Question: How to reference a specific column in an edge

### ISSUE THREAD

**Issue by mhrjimmy** [facebook/ent#782]
I noticed that when using `edge.To` and `edge.From`, `id` becomes a reference column by default.
How should i make the reference column be a different column.

For example in sql we do:  `REFERENCES users (UID) ON DELETE CASCADE`

**Comment by a8m** [comment]
Hey @mhrjimmy!

You can use the [`edge.StorageKey`](https://entgo.io/docs/schema-edges/#storagekey) and [`field.StorageKey`](https://entgo.io/docs/schema-fields/#storage-key) options for configuring the storage options for edges and their FK columns.

**Comment by gopkg-dev** [comment]
Hello, I ran into the same problem.
When UID is not the primary key, what should I do to use it as a foreign key.
