### ISSUE TITLE
Not able to query node with pg in the Node API in GraphQL Integration 

### ISSUE THREAD

**Issue by francismarcus** [facebook/ent#789]
When running the query node, [Node API](https://entgo.io/docs/graphql/#node-api)
```bash
pg          | 2020-09-21 16:04:07.147 UTC [45] ERROR:  syntax error at or near "`" at character 20
pg          | 2020-09-21 16:04:07.147 UTC [45] STATEMENT:  SELECT `type` FROM `ent_types` ORDER BY `id` ASC
```

**Comment by alexsn** [comment]
Query is comming from https://github.com/facebookincubator/ent-contrib/blob/master/entgql/template/node.tmpl#L189-L192, I'll take a look tomorrow.

**Comment by a8m** [comment]
Hey @francismarcus! https://github.com/facebookincubator/ent-contrib/pull/3 should solved this. I'll wait for @alexsn's review.

**Comment by francismarcus** [comment]
Hey @a8m! awesome, much appreciated. Great work with the integration doc btw

**Comment by a8m** [comment]
Patch was merged to ent-contrib. Please re-open if you still have troubles with it. Thanks
