### ISSUE TITLE
Ability to remove omitempty globally

### ISSUE THREAD

**Issue by napei** [facebook/ent#792]
I've run into this issue before when consuming JSON from Go, and it's unfortunately one of the pitfalls of how Go handles structs to JSON.

Unless I missed a config option, every struct that ent makes for each entity has `omitempy` tagged onto every field. This makes sense, to omit empty values. However to Go, `false`, `0`, `""` are all empty values for `bool`, `int/float`, `string`. 

This means that when marshalling the struct to JSON, these fields are ommitted. So a value of `false` when turned into JSON, is removed from the struct, which is fine but also implies it's `null` as JSON can have null/unset values and so can SQL, but Go can't unless everything is a pointer which causes headaches. When digesting this JSON with, say, JavaScript, these become `undefined` instead of their default value. The omission of these fields like `zero`, or `false`, provide a bad representation of what could actually be stored in the database as fields can be "unset" as well as be a default value.

Now in terms of `ent` this isn't technically a problem, because its purpose is not to interact with JSON, but instead with structs. There are situations where `omitempty` may be wanted. 

I've had success with the null package before (https://github.com/guregu/null) specifically when dealing with SQL values, as it marshalls nicely compared to the `sql` package which does not. I don't think this dramatic of a change is necessary however.

Consider the following example:
```go
type omitted struct {
	StringField string  `json:",omitempty"`
	IntField    int64   `json:",omitempty"`
	FloatField  float64 `json:",omitempty"`
	BoolField   bool    `json:",omitempty"`
}

type notOmitted struct {
	StringField string
	IntField    int64
	FloatField  float64
	BoolField   bool
}

func main() {
	o := omitted{
		StringField: "",
		IntField:    0,
		FloatField:  0,
		BoolField:   false,
	}

	// Prints {}
	jo, _ := json.Marshal(o)
	fmt.Println(string(jo))

	n := notOmitted{
		StringField: "",
		IntField:    0,
		FloatField:  0,
		BoolField:   false,
	}

	// Prints {"StringField":"","IntField":0,"FloatField":0,"BoolField":false}
	jn, _ := json.Marshal(n)
	fmt.Println(string(jn))
}
```

Let me know what you think.

**Comment by a8m** [comment]
Hey @napei!

You can use the [`StorageKey` option](https://entgo.io/docs/schema-fields/#storage-key) in order to override the JSON tag for fields, or you can use a custom template to override the template that generates these tags. 1st option is preferred IMO, and can be written with some helper as follows:


```go
func (T) Fields() []ent.Field {
	return fieldutil.WithStructTags(
		field.String("name"),
		field.String("address"),
		// ...
	)
}
 
// fieldutil.go
func WithStructTags(fields ...ent.Field) []ent.Field {
	for i := range fields {
		desc := fields[i].Descriptor()
		desc.Tag = fmt.Sprintf(`json:"%s"`, desc.Name)
	}
	return fields
}
```

Thanks for proposing this option, but unfortunately I don't think I want to add it to ent, as I'm trying to keep configuration options small and trying to avoid adding an option for each customization (others may want to control the tag format for example).

Anyway, I'm trying to encourage others to create OSS tools that can extend and customize ent (e.g. [ent-contrib](https://github.com/facebookincubator/ent-contrib)) - if you find this option useful for others, consider making it OSS. 

Closing, but feel free to continue the discussion or re-open if you have troubles with it.

**Comment by napei** [comment]
Hey @a8m that makes sense. Adding extra complexity isn't what I was after and yes I can just override the struct tags myself.

I was more taking the viewpoint that having `omitempty` on all fields can actually yield an invalid representation of the data stored in the DB and is thus it is incorrect in a sense.

For example Go supports `true` and `false` only for booleans (non-pointers), and subsequently does not even include the keys with a value of `false` in the marshalled JSON when `omitempty` is specified. In terms of the output JSON, this field does not exist and if accessed is `undefined` or `null` (not false) even if the value in the database is explicitly false. This also does not match the database correctly as unless a column is `not null` then booleans can be `true` `false` or `unknown` (https://www.postgresql.org/docs/12/datatype-boolean.html)

I recently had this issue representing products in a store, where their prices in JSON (used in API) were undefined instead of zero like I saved in the database.

**Comment by a8m** [comment]
> I was more taking the viewpoint that having omitempty on all fields can actually yield an invalid representation of the data stored in the DB and is thus it is incorrect in a sense.

Did you see the [`Nillable` option](https://entgo.io/docs/schema-fields/#nillable)?

**Comment by napei** [comment]
> > I was more taking the viewpoint that having omitempty on all fields can actually yield an invalid representation of the data stored in the DB and is thus it is incorrect in a sense.
> 
> Did you see the [`Nillable` option](https://entgo.io/docs/schema-fields/#nillable)?

Yeah I did look at that, however Nillable fields must also be optional, and I have several fields that are not optional and I don't want `omitempty`. I think for me the best alternative would be what you mentioned above with extending fields manually. 

Pointer fields in structs with `Nillable()` are omitted when they are `nil` instead of `false`, which again is not accurate because in JSON fields can be null as well as have a value.

**Comment by 0x4139** [comment]
> > I was more taking the viewpoint that having omitempty on all fields can actually yield an invalid representation of the data stored in the DB and is thus it is incorrect in a sense.
> 
> Did you see the [`Nillable` option](https://entgo.io/docs/schema-fields/#nillable)?

While the setting makes sense for most the types in go, it does not make sense for bool, for example having a bool field with a default value of false would not be consistent when serializing as it would be omited.
