### ISSUE TITLE
Question: Best practice to update an entity

### ISSUE THREAD

**Issue by roger2hk** [facebook/ent#793]
Let's say I have a `User` entity and a function to update the `User` entity. It seems like `UpdateOne` only updates the `updated_at` field if the `Set` functions are not used. Is there any built-in function to update all mutable entity fields?

```go
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}),
		field.Time("created_at").
			Default(time.Now).
			Immutable(),
		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now),
		field.Text("attribute1").
			Unique().
			Comment("attribute1"),
	}
}
```

```go
func UpdateUser(tx *ent.Tx, user *ent.User) (*ent.User, error) {
	return tx.User.
		UpdateOne(user).
		Save(ctx)
}
```

```go
user := GetUser(tx)
user.Attribute1 = "abc"
UpdateUser(tx, user)
```

**Comment by a8m** [comment]
Hey @roger2hk!

> It seems like UpdateOne only updates the updated_at field if the Set functions are not used.

Yeah, that's the default value if not value was provided to the builder. 

> Is there any built-in function to update all mutable entity fields?

I'm not sure I understand the question, to update all mutable fields to what values? they need to be provided somehow.

Also note that you can use the [Mutation](https://entgo.io/docs/crud/#mutation) option to share setters between create and update blocks. Alternatively, if you want to update the builders from some arbitrary object (let's a JSON input), you can use custom template as described in https://github.com/facebook/ent/issues/761#issuecomment-692562948.

**Comment by roger2hk** [comment]
Hey @a8m. That's a really quick reply. Assigning another value to `user.Attribute1` does not work as the underlying `UserMutation` does not know there is a change. Is that correct?

```go
user := GetUser(tx)
user.Attribute1 = "abc"
UpdateUser(tx, user)
```

It seems custom template is the only automated option to create a new function to figure out those changes and set them before executing the save operation.

**Comment by a8m** [comment]
> Assigning another value to user.Attribute1 does not work as the underlying UserMutation does not know there is a change. Is that correct?

No. All mutations must go through the builders. 

> It seems custom template is the only automated option to create a new function to figure out those changes and set them before executing the save operation.

Yes, using Go templates is pretty standard feature in ent to customize some of the codegen parts to your specific needs.

**Comment by a8m** [comment]
Closing, as this question was answered. Feel free to continue the discussion 😃

**Comment by seyedmmousavi** [comment]
It seems to be very useful feature or even great missing feature!
