### ISSUE TITLE
Migration to jackc/pgx for Postgresql ?

### ISSUE THREAD

**Issue by sundowndev** [facebook/ent#794]
Hi,

I've seen that [github.com/lib/pq](https://github.com/lib/pq#status) is not in active development anymore, and the usage of [pgx](https://github.com/jackc/pgx) is recommended by maintainers.

> This package is effectively in maintenance mode and is not actively developed. Small patches and features are only rarely reviewed and merged. We recommend using pgx which is actively maintained.

In the pgx's readme, a comparison is made with lib/pg :

> For prepared queries with small sets of simple data types, all drivers will have have similar performance. However, if prepared statements aren't being explicitly used, pgx can have a significant performance advantage due to automatic statement preparation. pgx also can perform better when using PostgreSQL-specific data types or query batching. See go_db_bench for some database driver benchmarks.

- Is pgx already compatible with ent ?
  - If no, is it planed to migrate to pgx as main postgres driver ?

**Comment by a8m** [comment]
Hey @sundowndev,
This issue already raised a few months ago - see https://github.com/facebook/ent/issues/605 and [entgo.io/pgx](https://entgo.io/docs/sql-integration/#use-pgx-with-postgresql). 

There should be no problems working with pgx. If you face any issues with it, please open an issue.
