### ISSUE TITLE
Feature: Fetch edges from gqlgen request

### ISSUE THREAD

**Issue by xabi93** [facebook/ent#806]
Hi!

We are thinking on moving to ent, and one thing that we miss, maybe it is and I don't find it 😛 it's the possibility to fetch edges of a graphql request from gqlgen.

e.g.
```graphql
type Query {
	company: Company
}

type Company {
	...
	workers: [Worker!]!
}
```
In this case to get workers gqlgen will create a new resolver (CompanyResolver) Workers to resolve the list of workers of a company doing a new query.
Is there any way to automatically ent handle this just in one query to the database? gqlgen adds all the requested fields in the context.

Thanks,

**Comment by a8m** [comment]
Hey @xabi93,

> Is there any way to automatically ent handle this just in one query to the database? gqlgen adds all the requested fields in the context.

It's actually supported by the [fields-collection](https://entgo.io/docs/graphql/#fields-collection) option in entgql. I'll add info about in the docs later today.
