### ISSUE TITLE
entgql: Noder doesn't support UUID Types

### ISSUE THREAD

**Issue by tankbusta** [facebook/ent#811]
Super excited to see ent support gqlgen (although I understand it's still early on :)) 

I was giving it a spin this evening and noticed when trying to create a model using `uuid.UUID` as the ID type, I got a bunch of type errors in some of the generated code.

```
ent/node.go:51:3: cannot use c.ID (type uuid.UUID) as type int in field value
ent/node.go:86:3: cannot use u.ID (type uuid.UUID) as type int in field value
ent/node.go:190:21: cannot use id (type int) as type uuid.UUID in argument to testmodel1.ID
ent/node.go:199:17: cannot use id (type int) as type uuid.UUID in argument to testmodel2.ID
ent/pagination.go:450:18: cannot use c.ID (type uuid.UUID) as type int in field value
ent/pagination.go:669:18: cannot use u.ID (type uuid.UUID) as type int in field value
```

So I changed the generator based from the documentation to use a custom Field TypeInfo to `TypeUUID`

```
// +build ignore

package main

import (
	"log"

	"github.com/facebook/ent/entc"
	"github.com/facebook/ent/entc/gen"
	"github.com/facebook/ent/schema/field"
	"github.com/facebookincubator/ent-contrib/entgql"
)

func main() {
	err := entc.Generate("./schema", &gen.Config{
		Templates: entgql.AllTemplates,
		IDType: &field.TypeInfo{
			Type: field.TypeUUID,
		},
	})
	if err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
}
```

Which got me a little bit further!

```
ent/node.go:180:26: cannot use id (type [16]byte) as type string in argument to strconv.Atoi
```

Looks like the culprit is located [here](https://github.com/facebookincubator/ent-contrib/blob/master/entgql/template/node.tmpl#L121-L127). As the type of `id` argument in `Noder` is `[16]byte`, this wont work but I'm wondering if there's an easy way to set this as `uuid.UUID` and use a Stringer interface to call Atoi? 

Thanks!

**Comment by a8m** [comment]
Hey @tankbusta and thanks for reporting this issue.

The Node API works only if you configure the migration to work with [universal-ids](https://entgo.io/docs/migrate/#universal-ids). Hence, the ID must be an int type (or converted to int). Because the type-resolver infer the NodeType from the ID value.

However, we actually discussed about adding support for custom type-resolvers, but in cases like this, users will need to decode the node-type somehow on the ID value.

If you can't use the NodeTemplate at the moment, you can choose specific templates that are relevant to you from [this list](https://github.com/facebookincubator/ent-contrib/blob/master/entgql/template.go#L26-L53).

**Comment by tankbusta** [comment]
So as I understand, using `universal-ids` still wont solve the problem with being able to use UUIDs as an ID with the GraphQL integration? It seems enabling that mode just partitions off IDs into a special table by model type as GraphQL requires "truly unique" IDs (SQL auto-incrementing IDs are not this)

My only option it seems at this time (and which you've pointed out) would be to fix up the template (which is fine I'm just trying to understand it completely)

**Comment by alexsn** [comment]
When using global IDs we're able to derive the node type given its ID which is not possible when using UUIDs. As @a8m mentioned, we could provide some hook in the node template so you could provide your own custom ID -> Type mapper. Alternatively you could fork the template and modify it to fit your use case.

**Comment by giautm** [comment]
In JS version of relay implement, they use base64(type + ":" + id) to provide Global ID. Can we do same thing with entgql? table name + entity's id (can be number string/uuid string)

```ts
/**
 * Takes a type name and an ID specific to that type name, and returns a
 * "global ID" that is unique among all types.
 */
export function toGlobalId(type: string, id: string): string {
  return base64([type, id].join(':'));
}

/**
 * Takes the "global ID" created by toGlobalID, and returns the type name and ID
 * used to create it.
 */
export function fromGlobalId(globalId: string): ResolvedGlobalId {
  const unbasedGlobalId = unbase64(globalId);
  const delimiterPos = unbasedGlobalId.indexOf(':');
  return {
    type: unbasedGlobalId.substring(0, delimiterPos),
    id: unbasedGlobalId.substring(delimiterPos + 1),
  };
}
```
Code copied from [here](https://github.com/graphql/graphql-relay-js/blob/f00bad1395eed1738264f41c35e3901dddff1559/src/node/node.js#L85-L104)

**Comment by a8m** [comment]
> It seems enabling that mode just partitions off IDs into a special table by model type as GraphQL requires "truly unique" IDs (SQL auto-incrementing IDs are not this)

@tankbusta - As mentioned in the [universal-ids doc](https://entgo.io/docs/migrate/#universal-ids), each node-table has a range of  1<<32 for its ids (in one database/shard). Hence, ids from different tables should not overlap in the same database.

Like I mentioned in the previous comment, I'll create a PR for making the `Type{Resolver/Mapper}` configurable for the client - How do you plan to resolve the NodeType from a UUID field? prefix it with additional information?

---

> In JS version of relay implement, they use base64(type + ":" + id) to provide Global ID. Can we do same thing with entgql? table name + entity's id (can be number string/uuid string)

@giautm - Like I mentioned above, we'll provide an API for configuring the `TypeResolver`, but the implementation is up to the user (should be simple to implement). I prefer the current approach, because it's working seamlessly with node-ids, and don't need to special handling in the client-side (or in the backend).

**Comment by a8m** [comment]
Hey @tankbusta  and @giautm,
A new change was added to entgql and docs was updated as well. Please go over it [here](https://entgo.io/docs/graphql/#node-api) and let me know if you still have troubles with it. Thanks

**Comment by Zn4rK** [comment]
I've just tried this. It almost works! 

I'm using Uuids (google/v4) right now, and it generates the following:

```go
// [...]
	ids, err = ix.QueryItem().
		Select(item.FieldID).
		Uuid.UUIDs(ctx)
// [...]
```

I've tracked it down to [this line](https://github.com/facebookincubator/ent-contrib/blob/0e6ac4cc1d3a8bcaaff85a21e3c804909d95ba1f/entgql/template/node.tmpl#L95).

**Comment by giautm** [comment]
Pagination still using int instead of `uuid.UUID`. Just change Todo's ID to uuid.UUID and run generate.
```
ent/pagination.go:687:12: cannot use t.ID (variable of type uuid.UUID) as int
```

```go
// Cursor of an edge type.
type Cursor struct {
	ID    int   `msgpack:"i"`
	Value Value `msgpack:"v,omitempty"`
}
```

**Comment by Zn4rK** [comment]
> Pagination still using int instead of `uuid.UUID`. Just change Todo's ID to uuid.UUID and run generate.

That's solvable with the IDType configuration option:
```go
package main

import (
	"log"
	"reflect"

	"github.com/facebook/ent/schema/field"
	"github.com/google/uuid"

	"github.com/facebook/ent/entc"
	"github.com/facebook/ent/entc/gen"
	"github.com/facebookincubator/ent-contrib/entgql"
)

func main() {
	rt := reflect.TypeOf(uuid.UUID{})

	err := entc.Generate("./schema", &gen.Config{
		Templates: entgql.AllTemplates,
		IDType: &field.TypeInfo{
			Type: field.TypeUUID,
			Ident:    rt.String(),
			PkgPath:  rt.PkgPath(),
		},
	})
	if err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
}
```

**Comment by giautm** [comment]
Hey @Zn4rK , that's worked. But I don't think we should do it manual? 🤔 

@a8m : I don't know how Node-ID can be convert to `gqlgen/graphql.IntID`/`gqlgen/graphql.ID`?

**Comment by a8m** [comment]
Thanks for reporting this guys. I'm giving it a look atm.

**Comment by a8m** [comment]
Please update to latest version of ent and ent-contrib and report any issues. Thanks for your feedback guys. 

> @a8m : I don't know how Node-ID can be convert to gqlgen/graphql.IntID/gqlgen/graphql.ID?

I'm not sure I understand the question @giautm, but here's an [example](https://entgo.io/docs/graphql/#gql-configuration) for a configuration we use.

**Comment by giautm** [comment]
Hi @a8m. I think there is a missing piece. In the relay spec, any Entity that implement Node interface should have ID as a GlobalID. It mean, If I use universel-id for Todo, the ID field also return a universel-id (GlobalID) instead Todo's ID. I didn't found any connection between universer-id and gqlgen ID. In JS, I implement that using a custom resolver for ID field - I'm new to gqlgen.

**Comment by alexsn** [comment]
In the todo app case a Todo id is a global id as we use universal ids in both [server](https://github.com/facebookincubator/ent-contrib/blob/master/entgql/internal/todo/server/server.go#L51) and [tests](https://github.com/facebookincubator/ent-contrib/blob/master/entgql/internal/todo/todo_test.go#L78).

**Comment by giautm** [comment]
Hey @alexsn, tks for explain. 

So, If I using custom NodeType configuare, there is no way to custom GlobalID for Todo?

**Comment by alexsn** [comment]
An important point to make is that an ID used in ent is not the same as a graphql ID. In the Todo case it is the same as ent provides global uniqueness but it doesn't have to be. Also note that in graphql an ID is just a scalar meaning some string that has no meaning outside the graphql server.

Now you can implement an ID over some go object (see [here](https://gqlgen.com/reference/scalars/#custom-scalars-with-user-defined-types) for docs) and make sure that the same go type provides a way to decode the node type so you can pass it to `. WithNodeType `.

Simple example:
```go
type GUID struct {
    Type string `json:"T"`
    UUID string `json:"I"`
}

func (guid GUID) MarshalGQL(w io.Writer) {
  // turn guid into a string
  data, _ := json.Marshal(guid)
  s := base64.StdEncoding.EncodeToString(data)
  // graphql ID is a scalar which must be quoted
  io.WriteString(w, strconv.Quote(s))
}

func (guid *GUID) UnmarshalGQL(v interface{}) error {
  str, ok := v.(string)
  if !ok {
    return fmt.Errorf("enum %T must be a string", v)
  }
  // reverse whatever MarshalGQL did to fill guid.
}
```
Now in gqlgen.yaml bind ID scalar to GUID:
```yaml
models:
  ID:
    model:
      - <full path for your GUID type>
```
After codegen gqlgen will use your GUID struct whenever a ID is used in graphql schema and calling `.Node` from GUID should be straightforward from there.

**Comment by giautm** [comment]
Adding a custom type for ID mean I have to dealing with database driver to marshal/unmarshal. :-/

**Comment by tankbusta** [comment]
I know this is closed but I just got around to giving this another try and it worked perfectly :)

I did have to update and use @Zn4rK's `entc.Generate` changes to get UUID's to work correctly with Cursors. Without setting `Ident` and `PkgPath` for the IDType, it would default to `[16]byte` and cause paginated queries to fail because it'd be using the bytes and not the string in queries. Is this something that should be included in documentation?

**Comment by giautm** [comment]
> > Pagination still using int instead of `uuid.UUID`. Just change Todo's ID to uuid.UUID and run generate.
> 
> That's solvable with the IDType configuration option

This issue was fixed by detecting IDType from the GQL Node, so you don't have to change `IDType` config anymore. 
https://github.com/ent/contrib/commit/6fc2c3622c06cceb165625c9583cc278da2a335e

**Comment by ysaakpr** [comment]
Are there any proper documentation when having mixed type int and uuid for id and want gql support? I am getting mixed type error when doing.
