### ISSUE TITLE
schema/field: Separate schema size limit separately, and add grapheme size limit

### ISSUE THREAD

**Issue by timonwong** [facebook/ent#829]
In stringBuilder, the descriptor "Size" is set by MaxLen, however, the validator for MaxLen validates utf8 sequence size, not the actual size in unicode.

**Comment by a8m** [comment]
Hey @timonwong and thanks for raising up this issue.

I agree with that and we should change it. The configuration should be provided separately using `schema.Annotations`. See https://github.com/facebook/ent/issues/663#issuecomment-692834740.

**Comment by a8m** [comment]
Hey @timonwong,
I've created https://github.com/facebook/ent/issues/943 for this issue. You're welcome to contribute this change or we can address it in the upcoming days. 

Closing.
