### ISSUE TITLE
Struct level validator for schemas

### ISSUE THREAD

**Issue by dilipkk-foyernet** [facebook/ent#831]
Currently, there is support for field validation which is good. We have a use case where to want to validate the entire struct by combining several fields. How can we achieve that?

**Comment by alexsn** [comment]
Use hooks.

**Comment by a8m** [comment]
Hey @dilipkk-foyernet!
Like @alexsn mentioned, you can use [hooks](https://entgo.io/docs/hooks/) for executing validations on single mutation, or you can use [transaction-hooks](https://entgo.io/docs/transactions/#hooks) for validating a change-set (multiple mutations in a transaction). 

Closing, but please feel free to comment and tag me if you need help with it.

**Comment by dilipkk-foyernet** [comment]
Thanks Ariel and Alex, I will check and get back to you if required.

**Comment by dilipkk-foyernet** [comment]
@a8m @alexsn I have checked hooks are providing the mutation operation support. I have a requirement about injecting some params from the auth context (based on user permissions) to both update and read APIs. It would be great to have hooks to support both read and write operations. Any suggestions on the same?

**Comment by a8m** [comment]
Hey @dilipkk-foyernet, see https://github.com/facebook/ent/issues/833#issuecomment-706348111, and let's continue the discussion in https://github.com/facebook/ent/issues/833.
