### ISSUE TITLE
i can't  entc describe ./ent/schema

### ISSUE THREAD

**Issue by oneirio115** [facebook/ent#845]
entc/load: # command-line-arguments
.entc\entc_github.com_User_app_ent_schema_1602529793.go:107:23: ed.Annotations undefined (type *edge.Descriptor has no field or method Annotations)
.entc\entc_github.com_User_app_ent_schema_1602529793.go:124:3: cannot use fd.Enums (type []string) as type map[string]string in field value
.entc\entc_github.com_User_app_ent_schema_1602529793.go:137:23: fd.Annotations undefined (type *field.Descriptor has no field or method Annotations)

**Comment by a8m** [comment]
Hey @oneirio115!

It looks like entc version is different from ent version. Please see [this doc](https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent) about how to keep the version compatible between entc and ent, or just use:

```
go run github.com/facebook/ent/cmd/entc describe ./ent/schema
```
