### ISSUE TITLE
Question: How to use gremlin as a storage-driver

### ISSUE THREAD

**Issue by jhole89** [facebook/ent#850]
### Description
I've recently moved to using ent however am seeing issues with the generated client.go, specifically `Open`. While trying to follow the CRUD example:

```go
import (
    "log"

    "<project>/ent"
)

func main() {
    client, err := ent.Open("gremlin", "http://localhost:8182")
    if err != nil {
        log.Fatal(err)
    }
}
```

Following this I receive the error `unsupported driver: "gremlin"` and when inspecting my generated client.go it seems that `dialect.Gremlin` is missing from the switch statement:

```go
// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}
```

### Versions
 - Go: 1.15
 - Ent 0.4.3

### Steps to reproduce
 - `entc init Foo`
 - `go generate ./ent`
 - check ./ent/client.go

**Comment by a8m** [comment]
Hey @jhole89,
The default storage driver for ent is SQL, if you want to use Gremlin, you can configure it using the `--storage` flag. See [this example](https://github.com/facebook/ent/blob/master/entc/integration/gremlin/ent/generate.go#L7).


Please note that as [mentioned in the website](https://entgo.io/docs/dialects/#gremlin), Gremlin is experimental atm.

**Comment by jhole89** [comment]
@a8m thanks. Can I suggest adding more info the page linked, maybe pointing to https://entgo.io/docs/code-gen/#code-generation-options with an explicit example? Requiring users to find at example listed in the source code (and one not listed under ./examples) isn't a great introduction.

**Comment by a8m** [comment]
Sure, we can add this. Thanks for the feedback 

(mentioning here #832, to not forget it when I'll update the website)

**Comment by jhole89** [comment]
@a8m Another suggested addition for the site: it would be good to add that if running standard gremlin-server (which uses int64 types for ID rather than Neptune's string ID type), the go generate command should be `//go:generate go run github.com/facebook/ent/cmd/entc generate --target . --storage=gremlin ./schema`.
