### ISSUE TITLE
proposal: auto-solve merge-conflict issues in codegen

### ISSUE THREAD

**Issue by a8m** [facebook/ent#852]
If the generated ent package contains merge-conflicts, there are 2 cases - If the user schema **doesn't** depend on the generated assets, running `go generate` solves the issue (and the issue is resolved). However, if the schema package imports the generated package (or depends on it somehow), the ent-loader won't be able to load the schema (due to syntax or build error), and resolving the merge-conflicts manually can take minutes.

I'm proposing to add an option (using feature-flag) to automate this process - 
1. When running codegen (on happy path), we generate a snapshot of the loaded schema (encoded JSON) and store it in `ent/internal`.
2. When executing the codegen, if we encounter a failure from the Go compiler (due to merge-conflicts), we execute the following steps:
    1. If the compile error comes from the schema, we report it to the user and exit.
    2. If the compile error comes from the generated package, we load the previous snapshot of the schema (and resolve the VCS conflicts with local version), and re-run codegen based on it. Then, we load the schema package again, and run codegen.

**Comment by a8m** [comment]
Closed with #862

**Comment by a8m** [comment]
@BrentChesny - can you share if that's your case?

> However, if the schema package imports the generated package (or depends on it somehow), the ent-loader won't be able to load the schema (due to syntax or build error), and resolving the merge-conflicts manually can take minutes.

**Comment by BrentChesny** [comment]
> @BrentChesny - can you share if that's your case?

That is indeed the case since we're using the privacy feature.

**Comment by a8m** [comment]
Can you please try enabling this option (see [example](https://github.com/facebook/ent/blob/master/entc/integration/privacy/ent/generate.go#L7)), and let me know if that solves the issue?

**Comment by BrentChesny** [comment]
There's a mistake in the snapshot merging I think. The new schema changes are lost. 

Problem is here I think: https://github.com/facebook/ent/pull/862/files#diff-376573e0768169bc9cca07b698b798013cfc63743fc05bbf1e15f2ec8f967e33R84

You're merging the original schema with itself 😄

**Comment by a8m** [comment]
> You're merging the original schema with itself 😄

😄 

Can you please send a patch for this?

**Comment by BrentChesny** [comment]
> > You're merging the original schema with itself 😄
> 
> 😄
> 
> Can you please send a patch for fixing this?

Will do 😄

**Comment by BrentChesny** [comment]
See #1022

**Comment by a8m** [comment]
@BrentChesny - please let me know if issue was resolved.

**Comment by BrentChesny** [comment]
Works like a charm 😊

**Comment by a8m** [comment]
Great to hear! Adding this to the website atm. 

Thanks for the reporting this and for fixing the issue 😃
