### ISSUE TITLE
entgql Aggregate queries

### ISSUE THREAD

**Issue by dilipkk-foyernet** [facebook/ent#857]
@a8m How to design aggregate queries with entgql?

Let say, we have users and pets. User can own many pets, we want to show in the user listing query that how many pets they own(count). Please help me with this example.

**Comment by a8m** [comment]
Hey @dilipkk-foyernet,
You can use the `Count` function for it as follows:

```go
count := user.QueryPets().Count(ctx)
```


It's part of the pagination-extension for gqlgen. See the [pets example](https://github.com/facebookincubator/ent-contrib/blob/79748a/entgql/internal/todo/ent/pagination.go#L368).

**Comment by dilipkk-foyernet** [comment]
Thanks @a8m I got this part. We need to handle this at application level right right, based collect field by gqlgen (like totalPetsCount). This is different from totalCount as this is users count.
My question is how to integrate this with the Connection object returns only User object as that is generate pagination extension.

**Comment by a8m** [comment]
> My question is how to integrate this with the Connection object returns only User object as that is generated pagination extension of entgql.

You can't add additional fields to the `UserConnection` that entgql generates (see [template-code](https://github.com/facebookincubator/ent-contrib/blob/master/entgql/template/pagination.tmpl#L234-L238)). You can either override this template, or return a new connection object for your use-case.

**Comment by a8m** [comment]
Closing since there's no action to take here. Feel free to continue the discussion if you have questions/comments about this.
