### ISSUE TITLE
Recurisve edge query

### ISSUE THREAD

**Issue by dilipkk-foyernet** [facebook/ent#863]
When we have an edge like a parent, children (self) how to query all the direct and indirect children of an item.
Example:
```go
// Fields returns task fields.
func (Task) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").
			Immutable(),
		field.String("status").
			GoType(types.TaskStatus("")).
			Annotations(
				entgql.OrderField("STATUS"),
			).NotEmpty(),
		field.String("priority").
			GoType(types.TaskPriority("")).
			Annotations(
				entgql.OrderField("PRIORITY"),
			).NotEmpty(),
		field.String("name").NotEmpty().MinLen(1).MaxLen(50),
		field.Text("description").Optional(),
	}
}

// Edges returns task edges.
func (Task) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("children", Task.Type).
			Annotations(entgql.Bind()).
			From("parent").
			Annotations(entgql.Bind()).
			Unique(),
	}
}
```
We can easily get direct children of parent task but how to get indirect children (children or children ....)?

**Comment by a8m** [comment]
Hey @dilipkk-foyernet, I think the following snippet should work (don't have time to test it atm):
```go
client.Task.Query().
    Where(
        task.Or(
            task.HasParentWith(task.ID(pid)),
            task.HasParentWith(task.HasParentWith(task.ID(pid))),
        ),
    ).
    All(ctx)
```

**Comment by dilipkk-foyernet** [comment]
Thanks @a8m, this is for 2 levels, but this is specifying the relation manually than leveraging recursive relation. We can do this with for now, but it would be good to have support for native recursive edge queries. Like getting all the tasks under a particular task, it may go 3-4 levels down. It is sometime good idea to manually specify also, as most of the cases it works except some rare cases.

**Comment by dilipkk-foyernet** [comment]
/https://www.postgresql.org/docs/current/queries-with.html is there plan to support common table expressions like "WITH"? @a8m
