### ISSUE TITLE
Bug: Creating an entity named `Client` doesn't go well

### ISSUE THREAD

**Issue by prmsrswt** [facebook/ent#873]
### What happened
I created a new entity named `Client` and ran `go generate ./ent` successfully, but the resulting code had errors, so the application won't build. On some investigation I found that we are using a struct named `Client` in the generated code already which was getting mixed with the `Client` entity.

### How to reproduce
- Create an entity named `Client`, `entc init Client`
- Generate code, `go generate ./ent`
- Now try building the code

### Expected behavior
`entc` should generate code which is works in this case. If this is not feasible then we can atleast throw a warning during `entc generate` or `entc init` if the entity name equals one of the "restricted" names.

**Comment by a8m** [comment]
Hey @prmsrswt and thanks for reporting this issue, it looks like the `Client` identifier is missing [in this list](https://github.com/facebook/ent/blob/master/entc/gen/type.go#L1253-L1276). Do you want contribute this change? 😃

**Comment by prmsrswt** [comment]
Well, why not. I'll create a PR for it.

**Comment by a8m** [comment]
Wonderful, thanks :)
