### ISSUE TITLE
Migrate maybe should create a index when `WithForeignKeys(false)` .

### ISSUE THREAD

**Issue by cocotyty** [facebook/ent#875]
Query becomes very slow if no index here.

**Comment by a8m** [comment]
Hey @cocotyty and thanks for raising up this issue.

Actually this was added by @day-dreams and I think it's necessary, but I'm not sure we should make it as default.
Maybe you can use the [`schema.Indexes`](https://entgo.io/docs/schema-indexes/) option for now? (it won't work for M2M edges).

**Comment by a8m** [comment]
Update: @cocotyty, is there any additional option you're proposing except using the `Indexes` option in the schema? Thanks

**Comment by a8m** [comment]
Hey, I was thinking about it and we're not going to support this.

If users want to ignore FKs, that's fine, but they'll have to implement it themselves or define it in ent/schema (both options are simple). Migration code is already too much complicated and I don't think this option should also be added. 

Closing, but feel free to continue the discussion if you need help with solving this issue 😃.
