### ISSUE TITLE
How to query array fields

### ISSUE THREAD

**Issue by dilipkk-foyernet** [facebook/ent#883]
Hi @a8m, Thanks for this library, we are using it for building a new product and we have a requirement of tagging(tags or labels) various resources of the product. We are planing keep `field.Strings("tags").Optional()` as a column on the resource which is tagable. The generated code, has only `TagsIsNil` and `TagsNotNil` for querying (filename: where.go), but we have the following use cases:
1. Resources with all given tags (all given tags should be present on that resource)
1. Resources with any given tags (any given tag should be present on that resource)
1. And negation of these above 2 use cases.

Please guide me on how to implement these use cases with ent.
Thanks in advance.

**Comment by dilipkk-foyernet** [comment]
Also, is Postgres arrays supported by ent framework like any or @> (contains) operators?

**Comment by a8m** [comment]
Hey @dilipkk-foyernet and welcome again 😃 

Currently, `Strings`, `Ints` and other slices are implemented using the `JSON` datatype and you can use the `sqljson` package for querying them - I just added the `ValueContains` predicate. 

You can also use custom templates for generating type-safe predicates for these fields. For example:

```go
func TagsContains(tag string) predicate.User {
    return predicate.User(func(s *sql.Selector) {
        s.Where(sqljson.ValueContains(user.FieldTags, tag))
    })
}
```
And then, use them as follows:

```go
client.User.Query().
    Where(
        user.TagsContains("foo"),
        user.Not(user.TagsContains("bar")),
    ).
    All(ctx)
```

**Comment by a8m** [comment]
@dilipkk-foyernet - does it answer you question? If so, can we close this issue?

**Comment by dilipkk-foyernet** [comment]
this is good, what about multiple tags, can we use `user.And` and `user.Or`conjuctions to achieve our use cases? @a8m also, does it work with sqlite or only postgres?

**Comment by a8m** [comment]
> can we use user.And and user.Orconjuctions to achieve our use cases? 

Yes

>  @a8m also, does it work with sqlite or only postgres?

Yes

Please report if you encounter any issue.

**Comment by dilipkk-foyernet** [comment]
sure I will give a try and closing the issue for now and if I encounter any problems, I will reopen it. Thanks a lot for the quick reply and solution.

**Comment by dilipkk-foyernet** [comment]
```go
func TagsContains(tag string) predicate.User {
    return predicate.User(func(s *sql.Selector) {
        s.Where(sqljson.ValueContains(user.FieldTags, tag))
    })
}
```
@a8m, can you please help me with this one, how to add this to template? I am already using entgql templates.

**Comment by dilipkk-foyernet** [comment]
```
{{ define "where/additional" }}
     {{- range $f := $.Fields }}
        	{{- if eq $f.Type.Ident "[]string" }}     
            {{ $arg := "v" }}
            {{ $func := print $f.StructField "Contains" }}
                // {{ $func }} checks if {{$f.StructField}} contains given value
                func {{ $func }}({{ $arg}} string) predicate.{{ $.Name }} {
                    return predicate.{{ $.Name }}(func(s *sql.Selector) {
                        s.Where(sqljson.ValueContains(s.C({{ $f.Constant }}), {{ $arg }}))
                    })
                }    
            {{ end }}
     {{ end }}
{{ end }}
```
I was able to generate the code snipet using this template.

**Comment by dilipkk-foyernet** [comment]
@a8m this is not working for postgres, query is generated with @>.
```
2021/02/05 09:18:42 driver.Query: query=SELECT DISTINCT "spaces"."id", "spaces"."created_at", "spaces"."updated_at", "spaces"."is_deleted", "spaces"."name", "spaces"."value", "spaces"."level", "spaces"."is_occupational_unit", "spaces"."parent_tags", "spaces"."alias" FROM "spaces" WHERE "spaces"."is_deleted" = $1 AND "spaces"."parent_tags" @> $2 ORDER BY "id" ASC args=[false "BUILDING:Venus"]
```
Field type for parentTags: `field.Strings("parentTags").Optional()`
It is stored as array: ["FLOOR_WING:A-5F", "FLOOR_WING:B-5F"] and column type is jsonb.

Can you please let me know if what is the issue here?

**Comment by iorlas** [comment]
Just in case it will be reviewed in the future: it would be nice to have support for the arrays of enums. But, I guess, we'll need to support native PostgreSQL arrays then.

**Comment by a8m** [comment]
Thanks for sharing this code @dilipkk-foyernet.

@iorlas, can you please elaborate what do you mean by "array of enums"? What type of predicates/fields are you missing today?

**Comment by iorlas** [comment]
@iorlas I would like to achieve similar scenarios:

```
CREATE TYPE thing AS ENUM ('a', 'b', 'c');

CREATE TABLE lecture_room (
...
  things thing[]
...
}
```

As far as I got the ent implementation, it is possible right now simply because of the ent implementation, creating enums as varchars. But if you will migrate to the proper enums, you will need to provide an option to use arrays with enums as well.

**Comment by vicky-swansi** [comment]
I also ran into similar problem, but I solved it by 

```
quotedColumn := s.Quote(sql.Table(yourTable.Table).C(yourTable.FieldColumn))
s.Where(sql.ExprP(fmt.Sprintf("%s @> ARRAY[?]", quotedColumn), columnValue))
```

cheers!

**Comment by vivekkswansi** [comment]
> I also ran into similar problem, but I solved it by
> 
> ```
> quotedColumn := s.Quote(sql.Table(yourTable.Table).C(yourTable.FieldColumn))
> s.Where(sql.ExprP(fmt.Sprintf("%s @> ARRAY[?]", quotedColumn), columnValue))
> ```
> 
> cheers!

Just replace ? by $1

**Comment by saiguptha2003** [comment]
@vicky-swansi Is it good practice to write code in the main codebase, or should we implement the method mentioned above by @a8m ?
