### ISSUE TITLE
How to add more fields in middle table with M2M relationship?

### ISSUE THREAD

**Issue by clearcodecn** [facebook/ent#885]
```
type Group struct {
	ent.Schema
}

// Edges of the Group.
func (Group) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To(`user`, User.Type),
	}
}

type User struct {
	ent.Schema
}

// Edges of the User.
func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("group", Group.Type).Ref(`user`),
	}
}


```

it will create `group_user` schema, how to add more fields to the schema? 
eg, group_admin, create_time ...

**Comment by a8m** [comment]
Hey @clearcodecn and thanks for opening this issue.

Right now, the option for attaching fields/properties to edges is not supported yet by the framework and it's part of our roadmap (see #46).

Closing, but I'll update this issue when it's done.
