### ISSUE TITLE
How to just update without SELECT entity

### ISSUE THREAD

**Issue by roffe** [facebook/ent#889]
.Save(ctx) returns the entity after updating it.
.Exec(ctx) does not return a entity but it under the hood still does a _, err := Save() which makes a single call update into 2 queries executed on the server
```
.Get()
2020/10/27 22:20:56 dialect.go:78: driver.Query: query=SELECT DISTINCT "devices"."id", "devices"."password", "devices"."os", "devices"."version", "devices"."model", "devices"."registered", "devices"."last_seen" FROM "devices" WHERE "devices"."id" = $1 LIMIT $2 args=[5712bc0b-d72d-472e-9ecf-a3c0497f84cd 2]
--------
.Exec()
2020/10/27 22:20:56 dialect.go:78: driver.Tx(14582947-b597-4ee2-ab5e-8696b0b218e5): started
2020/10/27 22:20:56 dialect.go:78: Tx(14582947-b597-4ee2-ab5e-8696b0b218e5).Exec: query=UPDATE "devices" SET "last_seen" = $1 WHERE "id" = $2 args=[2020-10-27 22:20:56.43097 +0100 CET m=+0.640263505 5712bc0b-d72d-472e-9ecf-a3c0497f84cd] <-- it should end here.
--- Why is this done?, exec can't return any entity so this SELECT is redundant ---
2020/10/27 22:20:56 dialect.go:78: Tx(14582947-b597-4ee2-ab5e-8696b0b218e5).Query: query=SELECT "id", "password", "os", "version", "model", "registered", "last_seen" FROM "devices" WHERE "id" = $1 args=[5712bc0b-d72d-472e-9ecf-a3c0497f84cd]
--------
```
How do i make ENT only do the UPDATE and not a SELECT directly after?

**Comment by a8m** [comment]
Hey @roffe!

The `Exec` method is just a wrapper around `Save`, but definitely can be improved.

You can use the [update builder](https://entgo.io/docs/crud/#update-many) to avoid the extra query as follows:

```go
err := client.Device.
    Update().
    Where(device.ID(id)).
    SetField(...).
    Exec(ctx)
```

**Comment by roffe** [comment]
@a8m thank you, i was using 
```go
if err := client.Device.UpdateOneID(id).
    SetField(...).
    Exec(ctx); err != nil {
    ...
}
```
I will use this pattern instead for when just updating and not needing a read-back of the value(s)

IMHO it would still be a good improvement if Exec() out-of-the-box wouldn't do a query under the hood after it saves the data :)

**Comment by a8m** [comment]
> IMHO it would still be a good improvement if Exec() out-of-the-box wouldn't do a query under the hood after it saves the data :)



Sure, I agree. I'll update this issue when we'll add it. Of course, you're welcome to contribute it if you want.
