### ISSUE TITLE
Failed to create a field of type Strings ([]string) - problem when migrating json field into MariaDB

### ISSUE THREAD

**Issue by gidiw** [facebook/ent#897]
I was trying to add a filed of type Strings to one of our schemas. 
After generating the code we got an error when launching our service (with MariaDB):

`validating schema: sql/schema: changing column type for "tags" is invalid (json != longtext)`

This was diagnosed by Ariel Mashraki as hitting the issue: https://mariadb.com/kb/en/json-data-type/

**Comment by a8m** [comment]
Thanks for reporting this @gidiw. I'll update you once it's fixed.

**Comment by a8m** [comment]
Solved with #1011 

Closing
