### ISSUE TITLE
question: Re-query entity inside "Update" action

### ISSUE THREAD

**Issue by longit644** [facebook/ent#903]
Hello,

I'm a little bit confused about the code of `sqlSave` in the builder for updating a single entity. Why do we need to make a query to get the result using `_spec.Assign` and `_spec.ScanValues`? Why don't you apply mutations to in-memory object?

https://github.com/facebook/ent/blob/2bd262a04cf07aea36d242025b291050994d983a/examples/o2o2types/ent/card_update.go#L385-L394

**Comment by a8m** [comment]
Hey @longit644, because it's possible to update a partial of the entity. For example:

```go
u, err := client.User.UpdateOneID(id).
    SetName("name").
    Save(ctx)
```

If you want to avoid this additional query, use the `Update` builder as mentioned in https://github.com/facebook/ent/issues/889#issuecomment-717770387.

**Comment by longit644** [comment]
That's awesome, thanks for the very fast response @a8m!

As mentioned in https://github.com/facebook/ent/issues/889#issuecomment-717770387, `Exec` method doesn't return new values of the update action. 

IMHO, we still use `Save` method without an additional query by applying mutations to `oldValue`.

https://github.com/facebook/ent/blob/2bd262a04cf07aea36d242025b291050994d983a/examples/o2o2types/ent/mutation.go#L490-L520

As the above code, `oldValue` will make a query to database when we use:
```go
client.User.UpdateOneID(id). 
    SetName("name").
    Save(ctx)
``` 
and don't when we use:

```go
user.Update(). 
    SetName("name").
    Save(ctx)
``` 

What do you think?

**Comment by a8m** [comment]
The `oldValue` function is executed in the mutation only when you try to load the old value of a field and it doesn't exist in the mutation state (unrelated to your use case). For example:

https://github.com/facebook/ent/blob/2bd262a04cf07aea36d242025b291050994d983a/entc/integration/hooks/ent/schema/user.go#L82-L92

**Comment by a8m** [comment]
Closing since there's no further action to take here. Feel free to continue the discussion if you still need help.

**Comment by longit644** [comment]
I'm sorry for the late reply. 

My Idea is to use `oldValue` for loading the entity's old value, then applying changes to create new value instead of make an additional query in `sqlgraph.UpdateNode`.

Ex:
```go
func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   user.Table,
			Columns: user.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: user.FieldID,
			},
		},
	}
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing User.ID for update")}
	}

	// Load the old value of entity.
	if _node, err = uuo.mutation.oldValue(ctx); err != nil {
		return nil, err
	}

	_spec.Node.ID.Value = id
	if value, ok := uuo.mutation.Age(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: user.FieldAge,
		})
		// Apply change to entity
		_node.Age = value
	}
	if value, ok := uuo.mutation.AddedAge(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: user.FieldAge,
		})
		// Apply change to entity
		_node.Age = _node.Age + value
	}
	if value, ok := uuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldName,
		})
		// Apply change to entity
		_node.Name = value
	}
	if uuo.mutation.CardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.CardTable,
			Columns: []string{user.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: card.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.CardTable,
			Columns: []string{user.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: card.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}

	// _node = &User{config: uuo.config}
	// _spec.Assign = _node.assignValues
	// _spec.ScanValues = _node.scanValues()

	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
```

By this way, we can save a query if oldValue exists in the mutation state.

**Comment by longit644** [comment]
Hi @a8m, what do think about it?

**Comment by a8m** [comment]
The [`oldValue`](https://github.com/facebook/ent/blob/c2cdc52946bc5685346be9f677c72337b7e8f80e/entc/gen/template/builder/mutation.tmpl#L65) function is used in the mutation to fetch the previous version of the object (or [use the local one](https://github.com/facebook/ent/blob/c2cdc52946bc5685346be9f677c72337b7e8f80e/entc/gen/template/builder/mutation.tmpl#L113-L121)).

If you want to override the [updater template](https://github.com/facebook/ent/blob/c2cdc52946bc5685346be9f677c72337b7e8f80e/entc/gen/template/dialect/sql/update.tmpl), you can set the `oldValue` fields from the mutation. I hope it answered your question.
