### ISSUE TITLE
question: StructTag on edges

### ISSUE THREAD

**Issue by masseelch** [facebook/ent#905]
This is my generated model. How to change the tag on `edges`?

```go
// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges UserEdges `json:"edges"` // <-- I want to edit this
}
```

**Comment by a8m** [comment]
Hey @masseelch, you can use the `edge.Annotation` for this. For example:

https://github.com/facebook/ent/blob/d3849f9eb7a9ff6e98f50970918718292e5df944/entc/integration/ent/schema/card.go#L21-L33

**Comment by a8m** [comment]
Closing this issue, but please feel free to re-open if doesn't answer your question or you need help with that.

**Comment by masseelch** [comment]
I don't really understand what schema.Annotation is.

**Comment by a8m** [comment]
You can read more about it here - https://entgo.io/docs/schema-annotations

But in your case, it’s simple, just follow the example I mentioned above - https://github.com/facebook/ent/issues/905#issuecomment-719499393

**Comment by masseelch** [comment]
Well, yes, it looks simple. But there is no `schema` that has an `Annotation` exported.

**Comment by masseelch** [comment]
Do i need to be on master branch for this?

**Comment by masseelch** [comment]
Yeah, that was it. Thanks. Working now :-)

**Comment by masseelch** [comment]
One little detail: Providing a struct tag on fields or edges will automatically add the `json` tag. With the `schema.Annotation` i have to add the tag myself. 

Expected behaviour or is this a bug?

**Comment by a8m** [comment]
> Expected behaviour or is this a bug?

This is intended. This annotation gives you the option to override the struct-tag.

> Do i need to be on master branch for this?

I'll release a new version in the upcoming days.
