### ISSUE TITLE
How to inject global logger like zap into schema hooks

### ISSUE THREAD

**Issue by dilipkk-foyernet** [facebook/ent#907]
Hi @a8m, I want to inject a zap logger to log any errors that occurred while executing hooks but not sure how to do this? can you guide me? Thanks in advance.

**Comment by a8m** [comment]
Hey @dilipkk-foyernet, if you're using [runtime hooks](https://entgo.io/docs/hooks/#runtime-hooks) you can just pass it when you initialize the hook as follows:

```go
func SomeHook(c Config) ent.Hook {
	hk := func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			v, err := next.Mutate(ctx, mutation)
			if err != nil {
				c.Log.Error(...)
				return nil, err
			}
			return v, nil
		})
	}
	return hook.On(hk, ent.OpCreate)
}
```

If you're using schema-hooks, you can add this info to the context.

Closing, but feel free to continue the discussion. You're also welcome to add it to #832 (FAQ issue).
