### ISSUE TITLE
How to update with "order" and "limit"?

### ISSUE THREAD

**Issue by Siceberg** [facebook/ent#908]
I want to implement the sql like:
`UPDATE cards SET respondent_name = "bar" order by RAND() limit 1`

But I have to use two SQLs actually to select one card record with "order" and "limit" and update it.

Is there any other way to do that with one SQL?

**Comment by a8m** [comment]
Hey @Siceberg,
This option is not supported by ent, and you need to implement it by yourself. If you want to add it to the generated code, you can use [custom templates](https://entgo.io/docs/templates/) for this.

Closing, but feel free to continue the discussion if you need help with that.

**Comment by Siceberg** [comment]
Thank for your response @a8m .
This option is temporarily not supported, or is it not supported in the plan?

**Comment by zhenruyan** [comment]
나 는 같은 문제 에 부 딪 혔 다.
