### ISSUE TITLE
Update save() not return the number of rows actually changed?

### ISSUE THREAD

**Issue by Siceberg** [facebook/ent#909]
There was one record in `Card` table:
Card(id=567c1356-1c15-4bbd-a6c3-bab791879f28, name=test)

With code:
```
n, err := client.Card.
	Update().
	Where(
		card.IDEQ(uuid.MustParse("567c1356-1c15-4bbd-a6c3-bab791879f28")),
	).
	SetName("test").
	Save(context.Background())
```
As n, I got 1, not 0

Usually, affected-rows means the number of rows actually changed.
Is my understanding wrong, or should I use other methods to get the number of rows actually changed?

**Comment by a8m** [comment]
Hey @Siceberg, you're are right, this piece of code need to be changed:

https://github.com/facebook/ent/blob/97432138608aaa4b0adf26f11d280804f5e007cf/dialect/sql/sqlgraph/graph.go#L694-L697

However, this change needs to be more sophisticated, because sometimes the entities in the table weren't changed, but their edges (in a different tables) were changed.

**Comment by Siceberg** [comment]
Is there any way I can get the number of changed rows of update?

**Comment by a8m** [comment]
OK, visiting back my previous question. This is intended as mentioned in the docs (_"returns the number of rows/vertices matched by this operation"_):

https://github.com/facebook/ent/blob/c2cdc52946bc5685346be9f677c72337b7e8f80e/entc/gen/template/builder/update.tmpl#L45-L46

> Query again after update? :(

I can't think on additional way for solving this atm.

**Comment by a8m** [comment]
Removed the "Question" label, let's continue the discussion in #912 here.

**Comment by a8m** [comment]
Hey @Siceberg, I created https://github.com/facebook/ent/pull/932 to fix this issue. I'll add another PR for updating the docs, and I'll close this issue.

**Comment by Siceberg** [comment]
Thanks a lot

**Comment by a8m** [comment]
Issue was addressed and landed to master. I'll release a new version in the upcoming days, but you're welcome to latest using:

```sh
go get github.com/facebook/ent@master
```
