### ISSUE TITLE
json-tag is missing on edges struct

### ISSUE THREAD

**Issue by masseelch** [facebook/ent#910]
When generating code the struct holding the edges information has no json tag.

```go
// SessionEdges holds the relations/edges for other nodes in the graph.
type SessionEdges struct {
	// User holds the value of the user edge.
	User *User
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}
```

Edges are rendered to CamelCase while fields rendered to snake_case. This is confusing and seems unintended.

**Comment by a8m** [comment]
Hey @masseelch, you can use the [`StructTag`](https://github.com/facebook/ent/blob/1b5f51b827095073a2b29228e56f73fa3ce0d49e/schema/edge/edge.go#L64-L67) option for adding the JSON tags.

I'll add it to the [FAQ](#832) page. Thanks

**Comment by masseelch** [comment]
Yes, i know. I just think its confusing, that the generator adds the JSON tags to the fields but not the edges. If i want a JSON-tag on the edge, i have to explicitly set it. The fields get it by default. 

This is what i meant. Sorry if I was not clear enough about it.

**Comment by thehowl** [comment]
@a8m sorry to necropost, but I was wondering: any reason why there is no default json tag on edges but only on fields? This feels inconsistent

**Comment by mattdavis90** [comment]
Sorry to add to a closed issue - I'm just starting out with ent and came across the same issue. The docs even imply that there should be a json-tag by default.
https://entgo.io/docs/schema-edges/#struct-tags
```go
edge.To("pets", Pet.Type).
    // Override the default json tag "pets" with "owner" for O2M relationship.
    StructTag(`json:"owner"`),
```

**Comment by a8m** [comment]
Hey all, and sorry @thehowl for the delayed response - I missed it for some reason. 

I added a patch for changing the behaviour according to the docs - https://github.com/facebook/ent/pull/1204.  Please update to latest if you need this:

```console
go get github.com/facebook/ent@master
```

Thanks for your feedback.
