### ISSUE TITLE
Update Many with one SQL

### ISSUE THREAD

**Issue by Siceberg** [facebook/ent#912]
When I try 

```
client.Card.
	Update().
	Where(
		card.IDEQ(uuid.MustParse("567c1356-1c15-4bbd-a6c3-bab791879f28")),
		card.NameEQ("test1"),
	).
	SetName("test").
	Save(context.Background())
```
I got log like:
2020/11/02 18:21:09 Tx(dac74d60-c526-4567-9228-f9e7fdf393ab).Query: query=SELECT `id` FROM `cards` WHERE `cards`.`id` = ? AND `cards`.`name` = ? args=[567c1356-1c15-4bbd-a6c3-bab791879f28 test1]
2020/11/02 18:21:09 Tx(dac74d60-c526-4567-9228-f9e7fdf393ab).Exec: query=UPDATE `cards` SET `name` = ? WHERE `id` = ? args=[test [53 54 55 99 49 51 53 54 45 49 99 49 53 45 52 98 98 100 45 97 54 99 51 45 98 97 98 55 57 49 56 55 57 102 50 56]]

Is there a way to implement updates using a SQL like:
UPDATE `cards` SET `name` = ? WHERE `cards`.`id` = "567c1356-1c15-4bbd-a6c3-bab791879f28" AND `cards`.`name` = "test1"

**Comment by a8m** [comment]
Hey @Siceberg, let's merge this issue to #909 and continue the discussion how this can be improved, because this happens due to the behaviour mentioned in https://github.com/facebook/ent/issues/909#issuecomment-720362195.
