### ISSUE TITLE
question: Is there a way to pass custom funcMap to external templates

### ISSUE THREAD

**Issue by masseelch** [facebook/ent#915]
See title.

**Comment by a8m** [comment]
Yes. See the [gen.Template](https://godoc.org/github.com/facebook/ent/entc/gen#Template) API and its usage [examples](https://github.com/facebook/ent/blob/master/examples/entcpkg/ent/entc.go).

Please feel free to add it to the [FAQ](https://entgo.io/docs/faq/) page in out website.

**Comment by rdeusser** [comment]
This doesn't appear to work. I've got
```go
err := entc.Generate("./schema", &gen.Config{
	Features: features,
	Templates: []*gen.Template{
		gen.MustParse(gen.NewTemplate("").Funcs(template.FuncMap{
			"mapHasKey": mapHasKey,
		}).ParseFiles("templates/options.tpl")),
	},
}, opts...)
```

and when I try to use that function in `options.tpl` I get this error:
```bash
template: options.tpl:25: function "mapHasKey" not defined
```
