### ISSUE TITLE
Set ROCKSDB Engine for MySQL Table Migration

### ISSUE THREAD

**Issue by dev681999** [facebook/ent#924]
Hi, I am trying to use this tool to create a database in MySQL. But, I want to use ROCKSDB as engine. I couldn't find any setting to set the engine when running migration.

GORM Does it like this - db.Set("gorm:table_options", "ENGINE=InnoDB").AutoMigrate(&User{})
https://gorm.io/docs/migration.html#content-inner

**Comment by a8m** [comment]
Hey @dev681999,
We don't support this option atm, but it's really simple to add. I can do it in the upcoming days, but if you want to contribute this change, here's where it needs to be added:

1\. Add another field named `Options` to the `entsql` annotation:
https://github.com/facebook/ent/blob/dea48a78eae387eaa7845480e6a3559029684a14/dialect/entsql/annotation.go#L11-L37

2\. Append this annotation option to the [table builder](https://github.com/facebook/ent/blob/762df65f11e82e99b7e33734fede32cdeae82f32/dialect/sql/schema/mysql.go#L178-L186) as follows:

```go
if opts := t.Annotation.Options; opts != "" {
	b.Options(opts)
}
```

**Comment by dooven** [comment]
If @dev681999 can't, i'd be glad to work on this :)

**Comment by a8m** [comment]
You're welcome to add this @dooven
