### ISSUE TITLE
question: How to extend ent

### ISSUE THREAD

**Issue by masseelch** [facebook/ent#930]
Hi there. As mentioned in #658 I'd like to provide a package to generate code for rest handlers. I have some work done already in [here](https://github.com/masseelch/go-api-akeleton).

Now i want to add the templates into its own package and make it easy to use with ent. My first idea was to wrap the make an own cli app, that uses the code-generation package like described [in your docs](https://entgo.io/docs/code-gen/#use-entc-as-a-package) and add my templates in.

Is this the right way to go or do you have some other not documented functionality to add custom templates from a package? It might be a good idea to add the possibility to define remote templates with you cli. What do you think?

**Comment by masseelch** [comment]
@a8m I started the project [here](https://github.com/masseelch/elk). Thoughts and ideas are welcome.

**Comment by a8m** [comment]
Hey @masseelch, please see the [GraphQL extension](https://github.com/facebookincubator/ent-contrib/tree/master/entgql) as a reference for such implementation.

**Comment by a8m** [comment]
> @a8m I started the project [here](https://github.com/masseelch/elk). Thoughts and ideas are welcome.

Sure, I'll give it a look. You're welcome to ping me privately if you want to discuss about some parts.
