### ISSUE TITLE
proposal: Generate non-go files

### ISSUE THREAD

**Issue by masseelch** [facebook/ent#931]
I'd like to be able to generate non go files.

**Comment by masseelch** [comment]
Nevermind. Did not see #367.

**Comment by a8m** [comment]
Hey @masseelch and thanks for proposing this feature.
This was actually answered before, and you can find it in https://github.com/facebook/ent/issues/780#issuecomment-695038170.

Also, you can see another example in https://github.com/facebook/ent/issues/367#issuecomment-701959271. 

Please let me know if you still need help with it 😃
