### ISSUE TITLE
Can ID field not be set ?

### ISSUE THREAD

**Issue by FakerGit** [facebook/ent#933]
Can the ID field not be set when an ID primary key is not required for a table?

![image](https://user-images.githubusercontent.com/13702295/98620746-d1d1d180-2340-11eb-8d9b-c6c08702f13b.png)

**Comment by a8m** [comment]
Hey @FakerGit, you can override the ID field in the schema as mentioned in the [this example](https://entgo.io/docs/schema-fields/#id-field).

If you want it make optional, use the [`Optional`](https://entgo.io/docs/schema-fields/#optional) method for this. Just note that we never test this scenario, so please let me know if it doesn't work for you. 

Closing, but feel free to continue the discussion.

**Comment by FakerGit** [comment]
> Hey @FakerGit, you can override the ID field in the schema as mentioned in the [this example](https://entgo.io/docs/schema-fields/#id-field).
> 
> If you want it make optional, use the [`Optional`](https://entgo.io/docs/schema-fields/#optional) method for this. Just note that we never test this scenario, so please let me know if it doesn't work for you.
> 
> Closing, but feel free to continue the discussion.

Thank you for your response. But what I meant was that I hope the id field doesn't appear in the structure, because it doesn't exist in my table。

**Comment by a8m** [comment]
> But what I meant was that I hope the id field doesn't appear in the structure, because it doesn't exist in my table。

It's not possible to use ent this way. The edges/associations logic is relying on the id field.

**Comment by errorhandler** [comment]
Hey @a8m just to jump in and check that my understanding is correct here.

We have a table that represents a pretty standard M2M style table (here pets have many verifications)
| pet_id | verification_id                      |
|--------|--------------------------------------|
| 5      | 8de4a7eb-d8fc-4f09-b040-3bd00eac21bb |
| 16     | eaed1bd8-ae1f-4ca4-94d0-4c06081e3cfa |

_However_ the `verification_id` comes from an external service.

Intuitively this table doesn't have a primary key.

Am I correct in my understanding that to use ent with such a model we'd have to add a primary key such as:
| id | pet_id | verification_id                      |
|----|--------|--------------------------------------|
| 1  | 5      | 8de4a7eb-d8fc-4f09-b040-3bd00eac21bb |
| 2  | 16     | eaed1bd8-ae1f-4ca4-94d0-4c06081e3cfa |

Thanks for all your work @a8m!

**Comment by a8m** [comment]
Hey @errorhandler and thanks for tagging me here - messages sometime get lost in email notifications. 

Regarding your example, you have a M2M relation between an entity generated by ent and other entity resides in a different datastore, right? (can you share what's the other datastore?)

Currently, for such cases, users can use either schema fields (for O2O and O2M relations) or additional schema type for representing a M2M relations (this is where #400 can be useful). However, I plan to add support for such "virtual edges" using the [storage-driver feature](https://github.com/facebook/ent/issues/676#issuecomment-676285602), so users will be able to configure a specific storage-type for each schema, and the relations between the different schemas will be managed by ent. Of course, the API will be limited for some storage-types (e.g. S3 or DynamoDB).
