### ISSUE TITLE
 sql/schema: scanning int value for column "id": converting driver.Value type string ("nextval('metadata_id_seq") to a int64: invalid syntax

### ISSUE THREAD

**Issue by fanpei91** [facebook/ent#934]
I have a existing table in Postgres like: 
```
mt=# \d+ metadata;
                                                         Table "public.metadata"
 Column  |          Type           | Collation | Nullable |               Default                | Storage  | Stats target | Description
---------+-------------------------+-----------+----------+--------------------------------------+----------+--------------+-------------
 id      | integer                 |           | not null | nextval('metadata_id_seq'::regclass) | plain    |              |
 service | character varying(2048) |           | not null |                                      | extended |              |
 fid     | character varying(2048) |           | not null |                                      | extended |              |
 meta    | text                    |           | not null | ''::text                             | extended |              |
Indexes:
    "metadata_fid_service" UNIQUE, btree (fid, service)
Access method: heap
```

Defined a schema:
```
// Metadata holds the schema definition for the Metadata entity.
type Metadata struct {
	ent.Schema
}

func (Metadata) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "metadata"},
	}
}

// Fields of the Metadata.
func (Metadata) Fields() []ent.Field {
	return []ent.Field{
		field.Uint64("id"),
		field.String("service").MaxLen(2048).NotEmpty(),
		field.String("fid").MaxLen(2048).NotEmpty(),
		field.Text("meta").Default(""),
	}
}

// Edges of the Metadata.
func (Metadata) Edges() []ent.Edge {
	return nil
}
```

Got 
```
sql/schema: scanning int value for column "id": converting driver.Value type string ("nextval('metadata_id_seq") to a int64: invalid syntax
```
when execute:

```
client.Schema.Create(context.Background())
```

What did I do wrong?

**Comment by a8m** [comment]
Hey @fanpei91 and thanks for opening this issue.

I'm not able to reproduce this on PostgreSQL, MySQL and SQLite. Can you please post here what are the database and the ent versions you use? Thanks

**Comment by ssoor** [comment]
> Hey @fanpei91 and thanks for opening this issue.
> 
> I'm not able to reproduce this on PostgreSQL, MySQL and SQLite. Can you please post here what are the database and the ent versions you use? Thanks

Hey @a8m ,I also encountered this problem.

The reason for my problem is that psql needs to use the sequence generator to realize the self-increment id. The value of the sequence generator set in the field is this.

```
 ALTER COLUMN "id" SET DEFAULT nextval('task_status_id_seq'::regclass);
```

It might be helpful to take a look at this [https://www.postgresql.org/docs/9.5/datatype-numeric.html#DATATYPE-SERIAL](https://www.postgresql.org/docs/9.5/datatype-numeric.html#DATATYPE-SERIAL)

**Comment by a8m** [comment]
Thanks for the reference @ssoor, I'll give it a look later this week.

**Comment by a8m** [comment]
Thanks for reporting this issue @fanpei91 and thanks @ssoor for your help.

#951 should resolve this, so please please update to latest master and report any issue.

**Comment by fanpei91** [comment]
@a8m  Thanks for your fix. I tested the latest version(commit: 77eaad0df615917188a40ab5f6479647b01b39bb) you asked for, but it causes another problem:
```
Error: sql/schema: cannot change primary key for table: "metadata"
```

This is the statements that how I created the existing table before using ent:
```sql
CREATE TABLE IF NOT EXISTS metadata (
    id serial NOT NULL,
    service varchar(128) not null,
    fid varchar(128) not null,
    meta text not null default ''
);
CREATE UNIQUE INDEX IF NOT EXISTS "metadata_fid_service" ON "metadata"("fid", "service");
```

The ent schema is the same as before:
```go
// Metadata holds the schema definition for the Metadata entity.
type Metadata struct {
	ent.Schema
}

func (Metadata) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "metadata"},
	}
}

// Fields of the Metadata.
func (Metadata) Fields() []ent.Field {
	return []ent.Field{
		field.Uint64("id"),
		field.String("service").MaxLen(2048).NotEmpty(),
		field.String("fid").MaxLen(2048).NotEmpty(),
		field.Text("meta").Default(""),
	}
}

// Edges of the Metadata.
func (Metadata) Edges() []ent.Edge {
	return nil
}
```

pgstgres version: 
```bash
# postgres --version
postgres (PostgreSQL) 13.0 (Debian 13.0-1.pgdg100+1)
```

**Comment by ssoor** [comment]
> @a8m Thanks for your fix. I tested the latest version(commit: [77eaad0](https://github.com/facebook/ent/commit/77eaad0df615917188a40ab5f6479647b01b39bb)) you asked for, but it causes another problem:
> 
> ```
> Error: sql/schema: cannot change primary key for table: "metadata"
> ```
> 
> This is the statements that how I created the existing table before using ent:
> 
> ```sql
> CREATE TABLE IF NOT EXISTS metadata (
>     id serial NOT NULL,
>     service varchar(128) not null,
>     fid varchar(128) not null,
>     meta text not null default ''
> );
> CREATE UNIQUE INDEX IF NOT EXISTS "metadata_fid_service" ON "metadata"("fid", "service");
> ```
> 
> The ent schema is the same as before:
> 
> ```go
> // Metadata holds the schema definition for the Metadata entity.
> type Metadata struct {
> 	ent.Schema
> }
> 
> func (Metadata) Annotations() []schema.Annotation {
> 	return []schema.Annotation{
> 		entsql.Annotation{Table: "metadata"},
> 	}
> }
> 
> // Fields of the Metadata.
> func (Metadata) Fields() []ent.Field {
> 	return []ent.Field{
> 		field.Uint64("id"),
> 		field.String("service").MaxLen(2048).NotEmpty(),
> 		field.String("fid").MaxLen(2048).NotEmpty(),
> 		field.Text("meta").Default(""),
> 	}
> }
> 
> // Edges of the Metadata.
> func (Metadata) Edges() []ent.Edge {
> 	return nil
> }
> ```
> 
> pgstgres version:
> 
> ```shell
> # postgres --version
> postgres (PostgreSQL) 13.0 (Debian 13.0-1.pgdg100+1)
> ```

This issue has been closed, if the repair results cause new problems, you may need to reopen issue , or create a new one.(Otherwise, no one will pay attention to it)
