### ISSUE TITLE
Question: Risk of SQL injection?

### ISSUE THREAD

**Issue by christopherwalter** [facebook/ent#945]
https://github.com/facebook/ent/blob/3038bb5ab12a7980434c778bdcbb23344213ba90/dialect/sql/builder.go#L8-L10

First of all, thanks for open-sourcing this library! I loved the ent framework when I was at FB and I'm excited about this Go version. 

My question is about the linked code in `sql/builder.go`, specifically the warning about the lack of SQL protection that's implemented in the generated SQL statements. In light of this, is there a recommendation for how we can guard against SQL injection? Is there potential for a fix here that changes the generated code to use `VALUES($1, ..)` alongside `db.Exec` for inserts?

Appreciate any insight, and thanks again!

**Comment by a8m** [comment]
Hey @christopherwalter!

> First of all, thanks for open-sourcing this library! I loved the ent framework when I was at FB and I'm excited about this Go version.

Wonderful! Feel free to suggest features or improvements if you think something is missing or can be improved (compared to the PHP version). 

Please see my comment from https://github.com/facebook/ent/issues/708#issuecomment-689360199:

> Thanks for the kind words jaredallard and christie-zhao 😃
> 
> > This solved it! I didn't know I can get TreeQuery outside. You are so helpful and awesome!!! 💯
> 
> You can add methods to the query builder from another file, and external-templates can help you to generate those methods. If you're struggling with it, create a temporary repository with a reproducible example (and some schema) and I'll create a PR for helping you with it.
> 
> > Just a small question, How do you prevent sql injection when using fmt.Sprintf?
> 
> In general, we use parametrized statement/queries for executing the SQL queries, so you don't need to worry if you're passing untrusted user-inputs to the builtin builder methods (like predicates, or when inserting data). You can see the generated SQL statement when calling `client.Debug()`.
> 
> However, the select expression is part of the SQL syntax and can't be passed using placeholders (`SELECT ? FROM ...`) - this is why we're accepting only fields for selection, and users should use the generated constants for passing those fields. We can enforce this, but injections are not expected to be on the SQL syntax level. There's a good discussion in the SQLAlchemy issue tracker - we can add a check for enforcing this (I'll do it) - **Update: the check was added.**
> 
> If you're adding new functionalities using external-templates, you should verify user-inputs or use placeholders where it's possible.
> 
> Regarding the question about `sql.Selector` in #742 - the query builders in `dialect/sql` are used for providing a statically-typed API for the generated ent code. They don't do syntax check nor escaping or other magic. It's considered an "internal" package of ent, and it's exposed only because the generated packages need them. I'll add it in doc comment.

Now, regarding your question:

>  Is there potential for a fix here that changes the generated code to use VALUES($1, ..) alongside db.Exec for inserts?

We already use parametrized statement/queries in the generated code, including INSERTs, and using the generated API is safe to use.

Closing because issues is addressed, but please feel free to continue the discussion or open it if you still it wasn't addressed.
