### ISSUE TITLE
Allow Migrations to handle integer to string

### ISSUE THREAD

**Issue by cliedeman** [facebook/ent#946]
Ent should be able to handle migrations from string to number and possibly attempt string to number 

Migration Error: 
```
sql/schema: changing column type for "some_column" is invalid (varchar != bigint)
```

**Comment by a8m** [comment]
Hey @cliedeman and thanks for raising up this issue.

Yeah, we should accept migration from numeric to string, but need to discuss about the other side.
Do you want to create a PR for supporting the "numeric to string" migration? If so, it will be great. 

BTW, I didn't forget #893 - I was a little bit busy lately and didn't find the time to review this (it's a pretty large PR).

**Comment by cliedeman** [comment]
Hi @a8m 

> Do you want to create a PR for supporting the "numeric to string" migration? If so, it will be great.
Sure I will can try it. The only consideration is how far we go with calculations before giving up.

Restrictions:
* Only allow integers 
* Do a basic calculation if the biggest number possible fits in the string and vice versa
* fail on any other case 

> BTW, I didn't forget #893 - I was a little bit busy lately and didn't find the time to review this (it's a pretty large PR).

Not a problem. I think about splitting it every now and then but its hard to exercise any of the changes without the full integration tests.

**Comment by cliedeman** [comment]
Added in #952 and #954
