### ISSUE TITLE
question: M2M aggregation query help

### ISSUE THREAD

**Issue by dilipkk-foyernet** [facebook/ent#959]
Hi @a8m,

I need some help following M2M aggregation query. Let us assume,[ users and groups](https://entgo.io/docs/schema-edges/#m2m-two-types) tables have M2M relationship between them.
I would like to output:
|Group Name     | User count   |
| :------------- | :----------: |
|  Developers | 10   |
| Managers  | 2  |

How to achieve this? 

Thanks a lot for your contribution to this library.

**Comment by a8m** [comment]
Hey @dilipkk-foyernet, I can give it a look later, but please see https://github.com/facebook/ent/issues/842#issuecomment-707896368 as a reference how to add custom logic to the query builder.

**Comment by dilipkk-foyernet** [comment]
@a8m also, if we want to get all group details along with user count then how to do. it is almost like getting entire group object and just users count. Is it possible?

**Comment by dilipkk-foyernet** [comment]
@a8m I understood, how to do this now, I have added additional fields template to create user_count field for group schema and then when querying for groups I am using aggregations to get the user count by joining group_users table with groups table.
