### ISSUE TITLE
[postgres] sql/schema: invalid type "inet"

### ISSUE THREAD

**Issue by hugmouse** [facebook/ent#963]
The Postgres database has [types](https://www.postgresql.org/docs/current/datatype-net-types.html) that are designed to store IP/CIDR — `inet`, `cidr`,`macaddr`,`macaddr8`. I wanted to use them, but I came across the next _possible_ bug, which I did not understand how to fix: `sql/schema: invalid type "inet" for column "last_login_ip”`

## Code example

`main.go` (copy-n-pasted from [sql.DB Integration](https://entgo.io/docs/sql-integration/#use-pgx-with-postgresql))

```go
package main

import (
	"ExampleIssue/ent"
	"context"
	"database/sql"
	"github.com/facebook/ent/dialect"
	"log"

	entsql "github.com/facebook/ent/dialect/sql"
	_ "github.com/jackc/pgx/v4/stdlib"
)

// Open new connection
func Open(databaseUrl string) *ent.Client {
	db, err := sql.Open("pgx", databaseUrl)
	if err != nil {
		log.Fatal(err)
	}

	// Create an ent.Driver from `db`.
	drv := entsql.OpenDB(dialect.Postgres, db)
	return ent.NewClient(ent.Driver(drv))
}

func main() {
	client := Open("postgresql://mysh@127.0.0.1/postgres")

	// Your code. For example:
	ctx := context.Background()
	if err := client.Schema.Create(ctx); err != nil {
		log.Fatal(err)
	}
	users, err := client.Example.Query().All(ctx)
	if err != nil {
		log.Fatal(err)
	}
	log.Println(users)
}
```

Example’s `schema`:

```go

package schema

[…]

// Fields of the Example.
func (Example) Fields() []ent.Field {
	return []ent.Field{
		field.String("last_login_ip").SchemaType(map[string]string{
			dialect.Postgres: "Inet",
		}).GoType(&pgtype.Inet{}),
	}
}

```

## Logs

Running for the first time:

```
mysh@mysh ExampleIssue % go run main.go
2020/11/20 17:01:50 []
```

Second time:

```
mysh@mysh ExampleIssue % go run main.go
2020/11/20 17:01:53 sql/schema: invalid type "inet" for column "last_login_ip"
exit status 1
```

**Comment by cliedeman** [comment]
@hugmouse migrations currently do not work with `SchemaType`. You will have to create the tables without using Schema.Create.

**Comment by a8m** [comment]
Hey @hugmouse and thanks for reporting this.

I think this should work if we’ll add these types to PostgreSQL migration (only if it’s not a user-defined type).

I’ll give it a look.

**Comment by cliedeman** [comment]
@a8m you will need the user defined column changes that are in #893. I can pull them out into a smaller pr. 

Unless you want to support schema type only for the initial migration?

**Comment by a8m** [comment]
> @a8m you will need the user defined column changes that are in #893. I can pull them out into a smaller pr.

Smaller PRs will make the review work much easier for me, but I prefer to finish #954 first. 

@hugmouse - I've added a small change that should make it work, can you please update to master and update us?

I'm going to focus the upcoming weeks on a few improvements for the migration, like supporting user-defined types (`field.Other(...)` in ent/schema), many other popular types including their predicates (like net or geo types), and schema versioning.

**Comment by hugmouse** [comment]
> @hugmouse - I've added a small change that should make it work, can you please update to master and update us?

Hi, @a8m. Now the database migration works, thank you!

**Comment by a8m** [comment]
Great and thanks for reporting this.

Closing.

**Comment by a8m** [comment]
Hey @hugmouse, I added a net-type example for our [FAQ page](https://entgo.io/docs/faq/#how-to-define-a-network-address-field-in-postgresql), would you mind adding your example [there](https://github.com/facebook/ent/blob/master/doc/md/faq.md) as well? Thanks
