### ISSUE TITLE
BUG: Enum "Redeclared in this package"

### ISSUE THREAD

**Issue by ftomza** [facebook/ent#966]
If the enumeration is set to one of the values as "**in**", then everything breaks.

```go
// Fields of the Message.
func (Message) Fields() []ent.Field {
	return []ent.Field{
		field.Text("text"),
		field.Enum("direction").
			Values("in", "out").
			Default("out"),
		field.Enum("status").
			Values("new", "deliver", "read").
			Default("new"),
	}
}
```

Since the generated constant intersects with the method

```go
// Direction values.
const (
	DirectionIn  Direction = "in"
	DirectionOut Direction = "out"
)

...


// DirectionIn applies the In predicate on the "direction" field.
func DirectionIn(vs ...Direction) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDirection), v...))
	})
}

```

**Comment by alexsn** [comment]
Hi @ftomza, you should override the generate go name for the direction enum by using `NamedValues`.

**Comment by ftomza** [comment]
Hi @alexsn, I have solved the problem of reassigning enum values so far. It seems to me that it is better to add the word **Enum** to the name of the enumeration constants, then it will be clear that this is an enumeration constant and the **Where** mechanisms will not break.

**Comment by a8m** [comment]
Thanks for the suggestion @ftomza, but I actually prefer to keep the enum naming as it today - naming conflicts (with predicates) is really rare and solvable using custom templates or `NamedValues`.

**Comment by alexsn** [comment]
Renaming the constant will break existing code as this is an exported constant. We added the `NamedValues` option to handle cases similar to the one you were facing.

**Comment by a8m** [comment]
Closing the issue as there's no action to take here form my side.

@ftomza, please free to re-open it if have any other issues with it.

**Comment by ftomza** [comment]
Thank you all for your help, I decided as @alexsn suggested.
