### ISSUE TITLE
ent cmd tool installation failure

### ISSUE THREAD

**Issue by sinnrrr** [facebook/ent#998]
`go get github.com/facebook/ent/cmd/ent`
throws this errror:

`go get github.com/facebook/ent/cmd/ent: module github.com/facebook/ent@upgrade found (v0.5.0), but does not contain package github.com/facebook/ent/cmd/ent`

**Comment by jason-shen** [comment]
same here, i think there is a change with this package

**Comment by sinnrrr** [comment]
yeah 2 hours ago the developers switched from `entc` to `ent`

**Comment by jason-shen** [comment]
> yeah, 2 hours ago the developers switched from `entc` to `ent`

i see that in the repo, but what does that mean

**Comment by a8m** [comment]
Hey @jason-shen and @sinnrrr, 
Let me release a new version and see if that fixes the problem. 

Some context about the issue - https://github.com/facebook/ent/issues/981

**Comment by a8m** [comment]
Can you please upgrade ent to latest (v0.5.1), and report here the status. Thanks

**Comment by sinnrrr** [comment]
@a8m running `go get -u github.com/facebook/ent/cmd/ent` did not help, so I cleared cache from $GOPATH, and all ran well
thanks for contributing to open source world!

**Comment by a8m** [comment]
Thanks for reporting this @sinnrrr 😃

**Comment by jason-shen** [comment]
all works as it should by just doing go get -u
